// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: errors/errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCodes определяет константы кодов ошибок ESF API.
// Используется для унификации и программной обработки ошибок.
// В protobuf это реализуется через enum.
type ErrorCode int32

const (
	// UNKNOWN - Неизвестная ошибка (по умолчанию)
	ErrorCode_ERROR_CODE_UNKNOWN ErrorCode = 0
	// InvalidRequest - Запрос имеет неверный формат или структуру.
	// Примеры: неверный JSON, отсутствуют обязательные поля
	ErrorCode_ERROR_CODE_INVALID_REQUEST ErrorCode = 1
	// MissingRequiredField - Отсутствует обязательное поле в запросе.
	// Указывает на то, что некоторые необходимые данные не предоставлены.
	ErrorCode_ERROR_CODE_MISSING_REQUIRED_FIELD ErrorCode = 2
	// InvalidFieldValue - Значение поля не соответствует ожидаемому формату.
	// Примеры: неверная дата, отрицательная сумма, недопустимый код
	ErrorCode_ERROR_CODE_INVALID_FIELD_VALUE ErrorCode = 3
	// InvalidDocumentType - Неверный тип документа (не Реализация/Приобретение/Корректировочная).
	ErrorCode_ERROR_CODE_INVALID_DOCUMENT_TYPE ErrorCode = 4
	// InvalidDocumentStatus - Операция недопустима для текущего статуса документа.
	// Примеры: попытка отредактировать подписанный документ
	ErrorCode_ERROR_CODE_INVALID_DOCUMENT_STATUS ErrorCode = 5
	// InvalidParty - Неверные реквизиты юридического лица или контрагента.
	// Примеры: несуществующий ИНН, пустое наименование
	ErrorCode_ERROR_CODE_INVALID_PARTY ErrorCode = 6
	// NotFound - Запрашиваемый ресурс не найден.
	// Общая ошибка "не найдено" для любых объектов.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 100
	// DocumentNotFound - Счет-фактура с указанным ID/UUID не найден.
	ErrorCode_ERROR_CODE_DOCUMENT_NOT_FOUND ErrorCode = 101
	// PartyNotFound - Юридическое лицо с указанным ИНН не найдено.
	ErrorCode_ERROR_CODE_PARTY_NOT_FOUND ErrorCode = 102
	// BankAccountNotFound - Банковский счет с указанным ID не найден.
	ErrorCode_ERROR_CODE_BANK_ACCOUNT_NOT_FOUND ErrorCode = 103
	// CatalogNotFound - Элемент справочника с указанным ID не найден.
	ErrorCode_ERROR_CODE_CATALOG_NOT_FOUND ErrorCode = 104
	// Unauthorized - Отсутствует авторизация или токен недействителен.
	// Требуется аутентификация для доступа к ресурсу.
	ErrorCode_ERROR_CODE_UNAUTHORIZED ErrorCode = 200
	// Forbidden - Доступ запрещен. У пользователя нет прав на операцию.
	// Пользователь аутентифицирован, но не авторизован.
	ErrorCode_ERROR_CODE_FORBIDDEN ErrorCode = 201
	// TokenExpired - Токен авторизации истек.
	ErrorCode_ERROR_CODE_TOKEN_EXPIRED ErrorCode = 202
	// InvalidToken - Токен авторизации невалиден или поврежден.
	ErrorCode_ERROR_CODE_INVALID_TOKEN ErrorCode = 203
	// DuplicateInvoiceNumber - Счет-фактура с таким номером уже существует.
	ErrorCode_ERROR_CODE_DUPLICATE_INVOICE_NUMBER ErrorCode = 300
	// InvalidTaxCalculation - Ошибка расчета налогов.
	// Суммы налогов не сходятся с ожидаемыми значениями.
	ErrorCode_ERROR_CODE_INVALID_TAX_CALCULATION ErrorCode = 301
	// InsufficientBalance - Недостаточный баланс для операции.
	ErrorCode_ERROR_CODE_INSUFFICIENT_BALANCE ErrorCode = 302
	// OperationNotAllowed - Операция недопустима в текущем состоянии.
	ErrorCode_ERROR_CODE_OPERATION_NOT_ALLOWED ErrorCode = 303
	// InternalServerError - Внутренняя ошибка сервера.
	// Общая ошибка сервера, когда что-то пошло не так.
	ErrorCode_ERROR_CODE_INTERNAL_SERVER_ERROR ErrorCode = 500
	// DatabaseError - Ошибка работы с базой данных.
	ErrorCode_ERROR_CODE_DATABASE_ERROR ErrorCode = 501
	// ServiceUnavailable - Сервис временно недоступен.
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE ErrorCode = 502
	// TimeoutError - Превышено время ожидания операции.
	ErrorCode_ERROR_CODE_TIMEOUT_ERROR ErrorCode = 503
	// ExternalServiceError - Ошибка внешнего сервиса (ТУНДУК, банки и т.д.).
	ErrorCode_ERROR_CODE_EXTERNAL_SERVICE_ERROR ErrorCode = 600
	// SignatureVerificationFailed - Не удалось проверить электронную подпись.
	ErrorCode_ERROR_CODE_SIGNATURE_VERIFICATION_FAILED ErrorCode = 601
	// TaxSystemError - Ошибка взаимодействия с налоговой системой.
	ErrorCode_ERROR_CODE_TAX_SYSTEM_ERROR ErrorCode = 602
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNKNOWN",
		1:   "ERROR_CODE_INVALID_REQUEST",
		2:   "ERROR_CODE_MISSING_REQUIRED_FIELD",
		3:   "ERROR_CODE_INVALID_FIELD_VALUE",
		4:   "ERROR_CODE_INVALID_DOCUMENT_TYPE",
		5:   "ERROR_CODE_INVALID_DOCUMENT_STATUS",
		6:   "ERROR_CODE_INVALID_PARTY",
		100: "ERROR_CODE_NOT_FOUND",
		101: "ERROR_CODE_DOCUMENT_NOT_FOUND",
		102: "ERROR_CODE_PARTY_NOT_FOUND",
		103: "ERROR_CODE_BANK_ACCOUNT_NOT_FOUND",
		104: "ERROR_CODE_CATALOG_NOT_FOUND",
		200: "ERROR_CODE_UNAUTHORIZED",
		201: "ERROR_CODE_FORBIDDEN",
		202: "ERROR_CODE_TOKEN_EXPIRED",
		203: "ERROR_CODE_INVALID_TOKEN",
		300: "ERROR_CODE_DUPLICATE_INVOICE_NUMBER",
		301: "ERROR_CODE_INVALID_TAX_CALCULATION",
		302: "ERROR_CODE_INSUFFICIENT_BALANCE",
		303: "ERROR_CODE_OPERATION_NOT_ALLOWED",
		500: "ERROR_CODE_INTERNAL_SERVER_ERROR",
		501: "ERROR_CODE_DATABASE_ERROR",
		502: "ERROR_CODE_SERVICE_UNAVAILABLE",
		503: "ERROR_CODE_TIMEOUT_ERROR",
		600: "ERROR_CODE_EXTERNAL_SERVICE_ERROR",
		601: "ERROR_CODE_SIGNATURE_VERIFICATION_FAILED",
		602: "ERROR_CODE_TAX_SYSTEM_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNKNOWN":                       0,
		"ERROR_CODE_INVALID_REQUEST":               1,
		"ERROR_CODE_MISSING_REQUIRED_FIELD":        2,
		"ERROR_CODE_INVALID_FIELD_VALUE":           3,
		"ERROR_CODE_INVALID_DOCUMENT_TYPE":         4,
		"ERROR_CODE_INVALID_DOCUMENT_STATUS":       5,
		"ERROR_CODE_INVALID_PARTY":                 6,
		"ERROR_CODE_NOT_FOUND":                     100,
		"ERROR_CODE_DOCUMENT_NOT_FOUND":            101,
		"ERROR_CODE_PARTY_NOT_FOUND":               102,
		"ERROR_CODE_BANK_ACCOUNT_NOT_FOUND":        103,
		"ERROR_CODE_CATALOG_NOT_FOUND":             104,
		"ERROR_CODE_UNAUTHORIZED":                  200,
		"ERROR_CODE_FORBIDDEN":                     201,
		"ERROR_CODE_TOKEN_EXPIRED":                 202,
		"ERROR_CODE_INVALID_TOKEN":                 203,
		"ERROR_CODE_DUPLICATE_INVOICE_NUMBER":      300,
		"ERROR_CODE_INVALID_TAX_CALCULATION":       301,
		"ERROR_CODE_INSUFFICIENT_BALANCE":          302,
		"ERROR_CODE_OPERATION_NOT_ALLOWED":         303,
		"ERROR_CODE_INTERNAL_SERVER_ERROR":         500,
		"ERROR_CODE_DATABASE_ERROR":                501,
		"ERROR_CODE_SERVICE_UNAVAILABLE":           502,
		"ERROR_CODE_TIMEOUT_ERROR":                 503,
		"ERROR_CODE_EXTERNAL_SERVICE_ERROR":        600,
		"ERROR_CODE_SIGNATURE_VERIFICATION_FAILED": 601,
		"ERROR_CODE_TAX_SYSTEM_ERROR":              602,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_errors_proto_rawDescGZIP(), []int{0}
}

// ErrorResponse представляет единую ошибку в ответе API.
// Структурированное представление ошибки с кодом, сообщением и деталями.
type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code - Код ошибки (машиночитаемый идентификатор).
	// Используется для программной обработки ошибок и локализации.
	// Примеры: "INVALID_REQUEST", "DOCUMENT_NOT_FOUND", "UNAUTHORIZED"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Message - Человеческое сообщение об ошибке на русском языке.
	// Короткое и понятное описание проблемы.
	// Примеры: "Документ не найден", "Неверный формат даты"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Details - Дополнительные детали об ошибке (опционально).
	// Может содержать более подробное объяснение, стек вызовов или
	// другую информацию для отладки (обычно только в режиме разработки).
	// Может быть пусто для ошибок в production.
	Details       string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_errors_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errors_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_errors_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// ValidationError представляет ошибку валидации конкретного поля.
// Используется для детализации ошибок валидации запросов.
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field - Название поля, в котором обнаружена ошибка.
	// Путь к полю в JSON-структуре (например, "invoice.details[0].price")
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Code - Код ошибки валидации для этого поля.
	Code ErrorCode `protobuf:"varint,2,opt,name=code,proto3,enum=errors.ErrorCode" json:"code,omitempty"`
	// Message - Человеческое описание ошибки.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_errors_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_errors_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNKNOWN
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MultipleErrorsResponse представляет множественные ошибки в ответе API.
// Используется, когда запрос содержит несколько ошибок валидации.
type MultipleErrorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors - Список всех ошибок, обнаруженных при обработке запроса.
	Errors []*ErrorResponse `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// ValidationErrors - Специфические ошибки валидации полей.
	ValidationErrors []*ValidationError `protobuf:"bytes,2,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MultipleErrorsResponse) Reset() {
	*x = MultipleErrorsResponse{}
	mi := &file_errors_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleErrorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleErrorsResponse) ProtoMessage() {}

func (x *MultipleErrorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_errors_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleErrorsResponse.ProtoReflect.Descriptor instead.
func (*MultipleErrorsResponse) Descriptor() ([]byte, []int) {
	return file_errors_errors_proto_rawDescGZIP(), []int{2}
}

func (x *MultipleErrorsResponse) GetErrors() []*ErrorResponse {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *MultipleErrorsResponse) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

var File_errors_errors_proto protoreflect.FileDescriptor

const file_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x13errors/errors.proto\x12\x06errors\"W\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"h\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12%\n" +
	"\x04code\x18\x02 \x01(\x0e2\x11.errors.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8d\x01\n" +
	"\x16MultipleErrorsResponse\x12-\n" +
	"\x06errors\x18\x01 \x03(\v2\x15.errors.ErrorResponseR\x06errors\x12D\n" +
	"\x11validation_errors\x18\x02 \x03(\v2\x17.errors.ValidationErrorR\x10validationErrors*\xbb\a\n" +
	"\tErrorCode\x12\x16\n" +
	"\x12ERROR_CODE_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x01\x12%\n" +
	"!ERROR_CODE_MISSING_REQUIRED_FIELD\x10\x02\x12\"\n" +
	"\x1eERROR_CODE_INVALID_FIELD_VALUE\x10\x03\x12$\n" +
	" ERROR_CODE_INVALID_DOCUMENT_TYPE\x10\x04\x12&\n" +
	"\"ERROR_CODE_INVALID_DOCUMENT_STATUS\x10\x05\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_PARTY\x10\x06\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10d\x12!\n" +
	"\x1dERROR_CODE_DOCUMENT_NOT_FOUND\x10e\x12\x1e\n" +
	"\x1aERROR_CODE_PARTY_NOT_FOUND\x10f\x12%\n" +
	"!ERROR_CODE_BANK_ACCOUNT_NOT_FOUND\x10g\x12 \n" +
	"\x1cERROR_CODE_CATALOG_NOT_FOUND\x10h\x12\x1c\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\xc8\x01\x12\x19\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\xc9\x01\x12\x1d\n" +
	"\x18ERROR_CODE_TOKEN_EXPIRED\x10\xca\x01\x12\x1d\n" +
	"\x18ERROR_CODE_INVALID_TOKEN\x10\xcb\x01\x12(\n" +
	"#ERROR_CODE_DUPLICATE_INVOICE_NUMBER\x10\xac\x02\x12'\n" +
	"\"ERROR_CODE_INVALID_TAX_CALCULATION\x10\xad\x02\x12$\n" +
	"\x1fERROR_CODE_INSUFFICIENT_BALANCE\x10\xae\x02\x12%\n" +
	" ERROR_CODE_OPERATION_NOT_ALLOWED\x10\xaf\x02\x12%\n" +
	" ERROR_CODE_INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x1e\n" +
	"\x19ERROR_CODE_DATABASE_ERROR\x10\xf5\x03\x12#\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10\xf6\x03\x12\x1d\n" +
	"\x18ERROR_CODE_TIMEOUT_ERROR\x10\xf7\x03\x12&\n" +
	"!ERROR_CODE_EXTERNAL_SERVICE_ERROR\x10\xd8\x04\x12-\n" +
	"(ERROR_CODE_SIGNATURE_VERIFICATION_FAILED\x10\xd9\x04\x12 \n" +
	"\x1bERROR_CODE_TAX_SYSTEM_ERROR\x10\xda\x04B6Z4github.com/rusgainew/tunduck-app-mk/proto-lib/errorsb\x06proto3"

var (
	file_errors_errors_proto_rawDescOnce sync.Once
	file_errors_errors_proto_rawDescData []byte
)

func file_errors_errors_proto_rawDescGZIP() []byte {
	file_errors_errors_proto_rawDescOnce.Do(func() {
		file_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_errors_proto_rawDesc), len(file_errors_errors_proto_rawDesc)))
	})
	return file_errors_errors_proto_rawDescData
}

var file_errors_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_errors_errors_proto_goTypes = []any{
	(ErrorCode)(0),                 // 0: errors.ErrorCode
	(*ErrorResponse)(nil),          // 1: errors.ErrorResponse
	(*ValidationError)(nil),        // 2: errors.ValidationError
	(*MultipleErrorsResponse)(nil), // 3: errors.MultipleErrorsResponse
}
var file_errors_errors_proto_depIdxs = []int32{
	0, // 0: errors.ValidationError.code:type_name -> errors.ErrorCode
	1, // 1: errors.MultipleErrorsResponse.errors:type_name -> errors.ErrorResponse
	2, // 2: errors.MultipleErrorsResponse.validation_errors:type_name -> errors.ValidationError
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_errors_errors_proto_init() }
func file_errors_errors_proto_init() {
	if File_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_errors_proto_rawDesc), len(file_errors_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_errors_proto_goTypes,
		DependencyIndexes: file_errors_errors_proto_depIdxs,
		EnumInfos:         file_errors_errors_proto_enumTypes,
		MessageInfos:      file_errors_errors_proto_msgTypes,
	}.Build()
	File_errors_errors_proto = out.File
	file_errors_errors_proto_goTypes = nil
	file_errors_errors_proto_depIdxs = nil
}
