// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/document_service.proto

package document

import (
	common "github.com/rusgainew/tunduck-app-mk/proto-lib/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type CreateDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDocumentRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDocumentRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentRequest) Reset() {
	*x = SendDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentRequest) ProtoMessage() {}

func (x *SendDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentRequest.ProtoReflect.Descriptor instead.
func (*SendDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SendDocumentRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SendDocumentRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApproveDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	Comments      string                 `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveDocumentRequest) Reset() {
	*x = ApproveDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveDocumentRequest) ProtoMessage() {}

func (x *ApproveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveDocumentRequest.ProtoReflect.Descriptor instead.
func (*ApproveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ApproveDocumentRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *ApproveDocumentRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type RejectDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,2,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectDocumentRequest) Reset() {
	*x = RejectDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectDocumentRequest) ProtoMessage() {}

func (x *RejectDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectDocumentRequest.ProtoReflect.Descriptor instead.
func (*RejectDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{5}
}

func (x *RejectDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RejectDocumentRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *RejectDocumentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ArchiveDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveDocumentRequest) Reset() {
	*x = ArchiveDocumentRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveDocumentRequest) ProtoMessage() {}

func (x *ArchiveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveDocumentRequest.ProtoReflect.Descriptor instead.
func (*ArchiveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{6}
}

func (x *ArchiveDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ListDocumentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // Filter: "draft", "sent", "approved", "archived"
	CreatedBy      string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // Filter by creator (optional)
	Page           int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PerPage        int32                  `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListDocumentsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListDocumentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDocumentsRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	PageInfo      *common.PageInfo       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_legacy_document_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetPageInfo() *common.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type AddDocumentEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentEntryRequest) Reset() {
	*x = AddDocumentEntryRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentEntryRequest) ProtoMessage() {}

func (x *AddDocumentEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentEntryRequest.ProtoReflect.Descriptor instead.
func (*AddDocumentEntryRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{9}
}

func (x *AddDocumentEntryRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AddDocumentEntryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddDocumentEntryRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateDocumentEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentEntryRequest) Reset() {
	*x = UpdateDocumentEntryRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentEntryRequest) ProtoMessage() {}

func (x *UpdateDocumentEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentEntryRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDocumentEntryRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *UpdateDocumentEntryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateDocumentEntryRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RemoveDocumentEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDocumentEntryRequest) Reset() {
	*x = RemoveDocumentEntryRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDocumentEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDocumentEntryRequest) ProtoMessage() {}

func (x *RemoveDocumentEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDocumentEntryRequest.ProtoReflect.Descriptor instead.
func (*RemoveDocumentEntryRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveDocumentEntryRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

type GetDocumentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentHistoryRequest) Reset() {
	*x = GetDocumentHistoryRequest{}
	mi := &file_legacy_document_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentHistoryRequest) ProtoMessage() {}

func (x *GetDocumentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetDocumentHistoryRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDocumentHistoryRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type DocumentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*DocumentVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	PageInfo      *common.PageInfo       `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentHistoryResponse) Reset() {
	*x = DocumentHistoryResponse{}
	mi := &file_legacy_document_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentHistoryResponse) ProtoMessage() {}

func (x *DocumentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentHistoryResponse.ProtoReflect.Descriptor instead.
func (*DocumentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_legacy_document_service_proto_rawDescGZIP(), []int{13}
}

func (x *DocumentHistoryResponse) GetVersions() []*DocumentVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *DocumentHistoryResponse) GetPageInfo() *common.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_legacy_document_service_proto protoreflect.FileDescriptor

const file_legacy_document_service_proto_rawDesc = "" +
	"\n" +
	"\x1dlegacy/document_service.proto\x12\fapi.document\x1a\x13legacy/common.proto\x1a\x15legacy/document.proto\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"\x8f\x01\n" +
	"\x15CreateDocumentRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\"W\n" +
	"\x15UpdateDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"s\n" +
	"\x13SendDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"v\n" +
	"\x16ApproveDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\tR\bcomments\"q\n" +
	"\x15RejectDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vrejected_by\x18\x02 \x01(\tR\n" +
	"rejectedBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"9\n" +
	"\x16ArchiveDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"\xa5\x01\n" +
	"\x14ListDocumentsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x05 \x01(\x05R\aperPage\"\x80\x01\n" +
	"\x15ListDocumentsResponse\x124\n" +
	"\tdocuments\x18\x01 \x03(\v2\x16.api.document.DocumentR\tdocuments\x121\n" +
	"\tpage_info\x18\x02 \x01(\v2\x14.api.common.PageInfoR\bpageInfo\"b\n" +
	"\x17AddDocumentEntryRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"_\n" +
	"\x1aUpdateDocumentEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"7\n" +
	"\x1aRemoveDocumentEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"k\n" +
	"\x19GetDocumentHistoryRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"\x87\x01\n" +
	"\x17DocumentHistoryResponse\x129\n" +
	"\bversions\x18\x01 \x03(\v2\x1d.api.document.DocumentVersionR\bversions\x121\n" +
	"\tpage_info\x18\x02 \x01(\v2\x14.api.common.PageInfoR\bpageInfo2\xfe\a\n" +
	"\x0fDocumentService\x12G\n" +
	"\vGetDocument\x12 .api.document.GetDocumentRequest\x1a\x16.api.document.Document\x12M\n" +
	"\x0eCreateDocument\x12#.api.document.CreateDocumentRequest\x1a\x16.api.document.Document\x12M\n" +
	"\x0eUpdateDocument\x12#.api.document.UpdateDocumentRequest\x1a\x16.api.document.Document\x12I\n" +
	"\fSendDocument\x12!.api.document.SendDocumentRequest\x1a\x16.api.document.Document\x12O\n" +
	"\x0fApproveDocument\x12$.api.document.ApproveDocumentRequest\x1a\x16.api.document.Document\x12M\n" +
	"\x0eRejectDocument\x12#.api.document.RejectDocumentRequest\x1a\x16.api.document.Document\x12O\n" +
	"\x0fArchiveDocument\x12$.api.document.ArchiveDocumentRequest\x1a\x16.api.document.Document\x12X\n" +
	"\rListDocuments\x12\".api.document.ListDocumentsRequest\x1a#.api.document.ListDocumentsResponse\x12V\n" +
	"\x10AddDocumentEntry\x12%.api.document.AddDocumentEntryRequest\x1a\x1b.api.document.DocumentEntry\x12\\\n" +
	"\x13UpdateDocumentEntry\x12(.api.document.UpdateDocumentEntryRequest\x1a\x1b.api.document.DocumentEntry\x12R\n" +
	"\x13RemoveDocumentEntry\x12(.api.document.RemoveDocumentEntryRequest\x1a\x11.api.common.Empty\x12d\n" +
	"\x12GetDocumentHistory\x12'.api.document.GetDocumentHistoryRequest\x1a%.api.document.DocumentHistoryResponseB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/documentb\x06proto3"

var (
	file_legacy_document_service_proto_rawDescOnce sync.Once
	file_legacy_document_service_proto_rawDescData []byte
)

func file_legacy_document_service_proto_rawDescGZIP() []byte {
	file_legacy_document_service_proto_rawDescOnce.Do(func() {
		file_legacy_document_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_document_service_proto_rawDesc), len(file_legacy_document_service_proto_rawDesc)))
	})
	return file_legacy_document_service_proto_rawDescData
}

var file_legacy_document_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_legacy_document_service_proto_goTypes = []any{
	(*GetDocumentRequest)(nil),         // 0: api.document.GetDocumentRequest
	(*CreateDocumentRequest)(nil),      // 1: api.document.CreateDocumentRequest
	(*UpdateDocumentRequest)(nil),      // 2: api.document.UpdateDocumentRequest
	(*SendDocumentRequest)(nil),        // 3: api.document.SendDocumentRequest
	(*ApproveDocumentRequest)(nil),     // 4: api.document.ApproveDocumentRequest
	(*RejectDocumentRequest)(nil),      // 5: api.document.RejectDocumentRequest
	(*ArchiveDocumentRequest)(nil),     // 6: api.document.ArchiveDocumentRequest
	(*ListDocumentsRequest)(nil),       // 7: api.document.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),      // 8: api.document.ListDocumentsResponse
	(*AddDocumentEntryRequest)(nil),    // 9: api.document.AddDocumentEntryRequest
	(*UpdateDocumentEntryRequest)(nil), // 10: api.document.UpdateDocumentEntryRequest
	(*RemoveDocumentEntryRequest)(nil), // 11: api.document.RemoveDocumentEntryRequest
	(*GetDocumentHistoryRequest)(nil),  // 12: api.document.GetDocumentHistoryRequest
	(*DocumentHistoryResponse)(nil),    // 13: api.document.DocumentHistoryResponse
	(*Document)(nil),                   // 14: api.document.Document
	(*common.PageInfo)(nil),            // 15: api.common.PageInfo
	(*DocumentVersion)(nil),            // 16: api.document.DocumentVersion
	(*DocumentEntry)(nil),              // 17: api.document.DocumentEntry
	(*common.Empty)(nil),               // 18: api.common.Empty
}
var file_legacy_document_service_proto_depIdxs = []int32{
	14, // 0: api.document.ListDocumentsResponse.documents:type_name -> api.document.Document
	15, // 1: api.document.ListDocumentsResponse.page_info:type_name -> api.common.PageInfo
	16, // 2: api.document.DocumentHistoryResponse.versions:type_name -> api.document.DocumentVersion
	15, // 3: api.document.DocumentHistoryResponse.page_info:type_name -> api.common.PageInfo
	0,  // 4: api.document.DocumentService.GetDocument:input_type -> api.document.GetDocumentRequest
	1,  // 5: api.document.DocumentService.CreateDocument:input_type -> api.document.CreateDocumentRequest
	2,  // 6: api.document.DocumentService.UpdateDocument:input_type -> api.document.UpdateDocumentRequest
	3,  // 7: api.document.DocumentService.SendDocument:input_type -> api.document.SendDocumentRequest
	4,  // 8: api.document.DocumentService.ApproveDocument:input_type -> api.document.ApproveDocumentRequest
	5,  // 9: api.document.DocumentService.RejectDocument:input_type -> api.document.RejectDocumentRequest
	6,  // 10: api.document.DocumentService.ArchiveDocument:input_type -> api.document.ArchiveDocumentRequest
	7,  // 11: api.document.DocumentService.ListDocuments:input_type -> api.document.ListDocumentsRequest
	9,  // 12: api.document.DocumentService.AddDocumentEntry:input_type -> api.document.AddDocumentEntryRequest
	10, // 13: api.document.DocumentService.UpdateDocumentEntry:input_type -> api.document.UpdateDocumentEntryRequest
	11, // 14: api.document.DocumentService.RemoveDocumentEntry:input_type -> api.document.RemoveDocumentEntryRequest
	12, // 15: api.document.DocumentService.GetDocumentHistory:input_type -> api.document.GetDocumentHistoryRequest
	14, // 16: api.document.DocumentService.GetDocument:output_type -> api.document.Document
	14, // 17: api.document.DocumentService.CreateDocument:output_type -> api.document.Document
	14, // 18: api.document.DocumentService.UpdateDocument:output_type -> api.document.Document
	14, // 19: api.document.DocumentService.SendDocument:output_type -> api.document.Document
	14, // 20: api.document.DocumentService.ApproveDocument:output_type -> api.document.Document
	14, // 21: api.document.DocumentService.RejectDocument:output_type -> api.document.Document
	14, // 22: api.document.DocumentService.ArchiveDocument:output_type -> api.document.Document
	8,  // 23: api.document.DocumentService.ListDocuments:output_type -> api.document.ListDocumentsResponse
	17, // 24: api.document.DocumentService.AddDocumentEntry:output_type -> api.document.DocumentEntry
	17, // 25: api.document.DocumentService.UpdateDocumentEntry:output_type -> api.document.DocumentEntry
	18, // 26: api.document.DocumentService.RemoveDocumentEntry:output_type -> api.common.Empty
	13, // 27: api.document.DocumentService.GetDocumentHistory:output_type -> api.document.DocumentHistoryResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_legacy_document_service_proto_init() }
func file_legacy_document_service_proto_init() {
	if File_legacy_document_service_proto != nil {
		return
	}
	file_legacy_document_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_document_service_proto_rawDesc), len(file_legacy_document_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_legacy_document_service_proto_goTypes,
		DependencyIndexes: file_legacy_document_service_proto_depIdxs,
		MessageInfos:      file_legacy_document_service_proto_msgTypes,
	}.Build()
	File_legacy_document_service_proto = out.File
	file_legacy_document_service_proto_goTypes = nil
	file_legacy_document_service_proto_depIdxs = nil
}
