// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/document.proto

package document

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Document aggregate root
// Represents a document in the system with workflow capability
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique document identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization ID (reference to company-service)
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Document title
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Document content
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Document status: "draft", "sent", "approved", "rejected", "archived"
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// User who created the document (reference to auth-service)
	CreatedBy string `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Current document owner/assignee
	AssignedTo string `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	// Document creation timestamp (Unix milliseconds)
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last updated timestamp (Unix milliseconds)
	UpdatedAt int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Last status change timestamp (Unix milliseconds)
	StatusChangedAt int64 `protobuf:"varint,10,opt,name=status_changed_at,json=statusChangedAt,proto3" json:"status_changed_at,omitempty"`
	// Document entries (key-value pairs)
	Entries []*DocumentEntry `protobuf:"bytes,11,rep,name=entries,proto3" json:"entries,omitempty"`
	// Document version number (for optimistic locking)
	Version int32 `protobuf:"varint,12,opt,name=version,proto3" json:"version,omitempty"`
	// Workflow metadata
	Workflow      *DocumentWorkflow `protobuf:"bytes,13,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_legacy_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Document) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Document) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Document) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Document) GetStatusChangedAt() int64 {
	if x != nil {
		return x.StatusChangedAt
	}
	return 0
}

func (x *Document) GetEntries() []*DocumentEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Document) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Document) GetWorkflow() *DocumentWorkflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

// *
// DocumentEntry value object
// Key-value pair within a document
type DocumentEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique entry identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Document ID
	DocumentId string `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// Entry key
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Entry value
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Creation timestamp (Unix milliseconds)
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last updated timestamp (Unix milliseconds)
	UpdatedAt     int64 `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentEntry) Reset() {
	*x = DocumentEntry{}
	mi := &file_legacy_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentEntry) ProtoMessage() {}

func (x *DocumentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentEntry.ProtoReflect.Descriptor instead.
func (*DocumentEntry) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentEntry) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DocumentEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DocumentEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DocumentEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// *
// DocumentWorkflow value object
// Handles document approval workflow state
type DocumentWorkflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current step in workflow
	CurrentStep string `protobuf:"bytes,1,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	// Approvers list
	Approvals []*ApprovalRequest `protobuf:"bytes,2,rep,name=approvals,proto3" json:"approvals,omitempty"`
	// Rejection reason (if rejected)
	RejectionReason string `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// Rejection timestamp (Unix milliseconds)
	RejectedAt int64 `protobuf:"varint,4,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"`
	// Approval timestamp (Unix milliseconds)
	ApprovedAt    int64 `protobuf:"varint,5,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentWorkflow) Reset() {
	*x = DocumentWorkflow{}
	mi := &file_legacy_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentWorkflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentWorkflow) ProtoMessage() {}

func (x *DocumentWorkflow) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentWorkflow.ProtoReflect.Descriptor instead.
func (*DocumentWorkflow) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentWorkflow) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *DocumentWorkflow) GetApprovals() []*ApprovalRequest {
	if x != nil {
		return x.Approvals
	}
	return nil
}

func (x *DocumentWorkflow) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *DocumentWorkflow) GetRejectedAt() int64 {
	if x != nil {
		return x.RejectedAt
	}
	return 0
}

func (x *DocumentWorkflow) GetApprovedAt() int64 {
	if x != nil {
		return x.ApprovedAt
	}
	return 0
}

// *
// ApprovalRequest value object
// Tracks approval status for each approver
type ApprovalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Approver user ID (reference to auth-service)
	ApproverId string `protobuf:"bytes,1,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	// Approval status: "pending", "approved", "rejected"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Approver comments
	Comments string `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	// When approval request was created (Unix milliseconds)
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When approval/rejection was done (Unix milliseconds)
	RespondedAt   int64 `protobuf:"varint,5,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_legacy_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovalRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ApprovalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApprovalRequest) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *ApprovalRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ApprovalRequest) GetRespondedAt() int64 {
	if x != nil {
		return x.RespondedAt
	}
	return 0
}

// *
// DocumentVersion value object
// Stores document revision history
type DocumentVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version number
	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Document snapshot at this version
	DocumentSnapshot *Document `protobuf:"bytes,2,opt,name=document_snapshot,json=documentSnapshot,proto3" json:"document_snapshot,omitempty"`
	// Changed by user ID
	ChangedBy string `protobuf:"bytes,3,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	// Change timestamp (Unix milliseconds)
	ChangedAt int64 `protobuf:"varint,4,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	// Change description
	ChangeDescription string `protobuf:"bytes,5,opt,name=change_description,json=changeDescription,proto3" json:"change_description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DocumentVersion) Reset() {
	*x = DocumentVersion{}
	mi := &file_legacy_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersion) ProtoMessage() {}

func (x *DocumentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersion.ProtoReflect.Descriptor instead.
func (*DocumentVersion) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentVersion) GetDocumentSnapshot() *Document {
	if x != nil {
		return x.DocumentSnapshot
	}
	return nil
}

func (x *DocumentVersion) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *DocumentVersion) GetChangedAt() int64 {
	if x != nil {
		return x.ChangedAt
	}
	return 0
}

func (x *DocumentVersion) GetChangeDescription() string {
	if x != nil {
		return x.ChangeDescription
	}
	return ""
}

// *
// DocumentTemplate value object
// Predefined document templates
type DocumentTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Template identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization ID (template owner)
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Template name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Template description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Template content (with placeholders like {{key}})
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// Template entries definition
	Entries []*TemplateEntry `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	// Is active template
	IsActive bool `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Creation timestamp (Unix milliseconds)
	CreatedAt     int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentTemplate) Reset() {
	*x = DocumentTemplate{}
	mi := &file_legacy_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentTemplate) ProtoMessage() {}

func (x *DocumentTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentTemplate.ProtoReflect.Descriptor instead.
func (*DocumentTemplate) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentTemplate) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DocumentTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentTemplate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentTemplate) GetEntries() []*TemplateEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *DocumentTemplate) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DocumentTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// *
// TemplateEntry value object
// Defines template field structure
type TemplateEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field key name
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Field display label
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Field type: "text", "number", "date", "select", "textarea"
	FieldType string `protobuf:"bytes,3,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	// Is required field
	Required bool `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	// Field order
	Order int32 `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	// Field validation pattern (regex)
	ValidationPattern string `protobuf:"bytes,6,opt,name=validation_pattern,json=validationPattern,proto3" json:"validation_pattern,omitempty"`
	// Field default value
	DefaultValue  string `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateEntry) Reset() {
	*x = TemplateEntry{}
	mi := &file_legacy_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateEntry) ProtoMessage() {}

func (x *TemplateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateEntry.ProtoReflect.Descriptor instead.
func (*TemplateEntry) Descriptor() ([]byte, []int) {
	return file_legacy_document_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TemplateEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TemplateEntry) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *TemplateEntry) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *TemplateEntry) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *TemplateEntry) GetValidationPattern() string {
	if x != nil {
		return x.ValidationPattern
	}
	return ""
}

func (x *TemplateEntry) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

var File_legacy_document_proto protoreflect.FileDescriptor

const file_legacy_document_proto_rawDesc = "" +
	"\n" +
	"\x15legacy/document.proto\x12\fapi.document\"\xc2\x03\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12*\n" +
	"\x11status_changed_at\x18\n" +
	" \x01(\x03R\x0fstatusChangedAt\x125\n" +
	"\aentries\x18\v \x03(\v2\x1b.api.document.DocumentEntryR\aentries\x12\x18\n" +
	"\aversion\x18\f \x01(\x05R\aversion\x12:\n" +
	"\bworkflow\x18\r \x01(\v2\x1e.api.document.DocumentWorkflowR\bworkflow\"\xa6\x01\n" +
	"\rDocumentEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xdf\x01\n" +
	"\x10DocumentWorkflow\x12!\n" +
	"\fcurrent_step\x18\x01 \x01(\tR\vcurrentStep\x12;\n" +
	"\tapprovals\x18\x02 \x03(\v2\x1d.api.document.ApprovalRequestR\tapprovals\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vrejected_at\x18\x04 \x01(\x03R\n" +
	"rejectedAt\x12\x1f\n" +
	"\vapproved_at\x18\x05 \x01(\x03R\n" +
	"approvedAt\"\xa8\x01\n" +
	"\x0fApprovalRequest\x12\x1f\n" +
	"\vapprover_id\x18\x01 \x01(\tR\n" +
	"approverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\tR\bcomments\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12!\n" +
	"\fresponded_at\x18\x05 \x01(\x03R\vrespondedAt\"\xdd\x01\n" +
	"\x0fDocumentVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12C\n" +
	"\x11document_snapshot\x18\x02 \x01(\v2\x16.api.document.DocumentR\x10documentSnapshot\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x03 \x01(\tR\tchangedBy\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x04 \x01(\x03R\tchangedAt\x12-\n" +
	"\x12change_description\x18\x05 \x01(\tR\x11changeDescription\"\x8e\x02\n" +
	"\x10DocumentTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x125\n" +
	"\aentries\x18\x06 \x03(\v2\x1b.api.document.TemplateEntryR\aentries\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\xdc\x01\n" +
	"\rTemplateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"field_type\x18\x03 \x01(\tR\tfieldType\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\x12-\n" +
	"\x12validation_pattern\x18\x06 \x01(\tR\x11validationPattern\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValueB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/documentb\x06proto3"

var (
	file_legacy_document_proto_rawDescOnce sync.Once
	file_legacy_document_proto_rawDescData []byte
)

func file_legacy_document_proto_rawDescGZIP() []byte {
	file_legacy_document_proto_rawDescOnce.Do(func() {
		file_legacy_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_document_proto_rawDesc), len(file_legacy_document_proto_rawDesc)))
	})
	return file_legacy_document_proto_rawDescData
}

var file_legacy_document_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_legacy_document_proto_goTypes = []any{
	(*Document)(nil),         // 0: api.document.Document
	(*DocumentEntry)(nil),    // 1: api.document.DocumentEntry
	(*DocumentWorkflow)(nil), // 2: api.document.DocumentWorkflow
	(*ApprovalRequest)(nil),  // 3: api.document.ApprovalRequest
	(*DocumentVersion)(nil),  // 4: api.document.DocumentVersion
	(*DocumentTemplate)(nil), // 5: api.document.DocumentTemplate
	(*TemplateEntry)(nil),    // 6: api.document.TemplateEntry
}
var file_legacy_document_proto_depIdxs = []int32{
	1, // 0: api.document.Document.entries:type_name -> api.document.DocumentEntry
	2, // 1: api.document.Document.workflow:type_name -> api.document.DocumentWorkflow
	3, // 2: api.document.DocumentWorkflow.approvals:type_name -> api.document.ApprovalRequest
	0, // 3: api.document.DocumentVersion.document_snapshot:type_name -> api.document.Document
	6, // 4: api.document.DocumentTemplate.entries:type_name -> api.document.TemplateEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_legacy_document_proto_init() }
func file_legacy_document_proto_init() {
	if File_legacy_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_document_proto_rawDesc), len(file_legacy_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_legacy_document_proto_goTypes,
		DependencyIndexes: file_legacy_document_proto_depIdxs,
		MessageInfos:      file_legacy_document_proto_msgTypes,
	}.Build()
	File_legacy_document_proto = out.File
	file_legacy_document_proto_goTypes = nil
	file_legacy_document_proto_depIdxs = nil
}
