// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/company.proto

package company

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Organization aggregate root
// Represents a company/organization in the system
type Organization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique organization identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Organization description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Owner user ID (reference to auth-service)
	OwnerId string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Total number of members
	MemberCount int32 `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	// Organization creation timestamp (Unix milliseconds)
	CreatedAt int64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last updated timestamp (Unix milliseconds)
	UpdatedAt int64 `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Organization status: "active", "inactive", "archived"
	Status        string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_legacy_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_legacy_company_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Organization) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Organization) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Organization) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Organization) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// *
// Employee aggregate root
// Represents user's membership in an organization
type Employee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique employee identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization ID
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// User ID (reference to auth-service)
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Employee role: "member", "manager", "admin"
	Role string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// Employee status: "active", "inactive"
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Position or job title
	Position string `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	// Department (optional)
	Department string `protobuf:"bytes,7,opt,name=department,proto3" json:"department,omitempty"`
	// Join date timestamp (Unix milliseconds)
	JoinedAt int64 `protobuf:"varint,8,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	// Last activity timestamp (Unix milliseconds)
	LastActiveAt  int64 `protobuf:"varint,9,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_legacy_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_legacy_company_proto_rawDescGZIP(), []int{1}
}

func (x *Employee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Employee) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Employee) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Employee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Employee) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Employee) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Employee) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Employee) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *Employee) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

// *
// Department value object
// Organizational structure unit
type Department struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique department identifier (UUID)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization ID
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Department name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Department description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Parent department ID (for hierarchy)
	ParentId string `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Manager employee ID
	ManagerId string `protobuf:"bytes,6,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	// Creation timestamp (Unix milliseconds)
	CreatedAt     int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_legacy_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_legacy_company_proto_rawDescGZIP(), []int{2}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Department) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Department) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *Department) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// *
// Role value object
// Organization-specific role
type OrganizationRole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization ID
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Role name: "member", "manager", "admin"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Role description
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Permissions codes
	Permissions []string `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Is this a system role (cannot be deleted)
	IsSystem bool `protobuf:"varint,6,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	// Creation timestamp (Unix milliseconds)
	CreatedAt     int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationRole) Reset() {
	*x = OrganizationRole{}
	mi := &file_legacy_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationRole) ProtoMessage() {}

func (x *OrganizationRole) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationRole.ProtoReflect.Descriptor instead.
func (*OrganizationRole) Descriptor() ([]byte, []int) {
	return file_legacy_company_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationRole) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationRole) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *OrganizationRole) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *OrganizationRole) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_legacy_company_proto protoreflect.FileDescriptor

const file_legacy_company_proto_rawDesc = "" +
	"\n" +
	"\x14legacy/company.proto\x12\vapi.company\"\xe8\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12!\n" +
	"\fmember_count\x18\x05 \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x87\x02\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\a \x01(\tR\n" +
	"department\x12\x1b\n" +
	"\tjoined_at\x18\b \x01(\x03R\bjoinedAt\x12$\n" +
	"\x0elast_active_at\x18\t \x01(\x03R\flastActiveAt\"\xd6\x01\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x06 \x01(\tR\tmanagerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xdf\x01\n" +
	"\x10OrganizationRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1b\n" +
	"\tis_system\x18\x06 \x01(\bR\bisSystem\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAtB7Z5github.com/rusgainew/tunduck-app-mk/proto-lib/companyb\x06proto3"

var (
	file_legacy_company_proto_rawDescOnce sync.Once
	file_legacy_company_proto_rawDescData []byte
)

func file_legacy_company_proto_rawDescGZIP() []byte {
	file_legacy_company_proto_rawDescOnce.Do(func() {
		file_legacy_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_company_proto_rawDesc), len(file_legacy_company_proto_rawDesc)))
	})
	return file_legacy_company_proto_rawDescData
}

var file_legacy_company_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_legacy_company_proto_goTypes = []any{
	(*Organization)(nil),     // 0: api.company.Organization
	(*Employee)(nil),         // 1: api.company.Employee
	(*Department)(nil),       // 2: api.company.Department
	(*OrganizationRole)(nil), // 3: api.company.OrganizationRole
}
var file_legacy_company_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_legacy_company_proto_init() }
func file_legacy_company_proto_init() {
	if File_legacy_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_company_proto_rawDesc), len(file_legacy_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_legacy_company_proto_goTypes,
		DependencyIndexes: file_legacy_company_proto_depIdxs,
		MessageInfos:      file_legacy_company_proto_msgTypes,
	}.Build()
	File_legacy_company_proto = out.File
	file_legacy_company_proto_goTypes = nil
	file_legacy_company_proto_depIdxs = nil
}
