// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/bank.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bank представляет информацию о банке/кредитном учреждении.
// Используется для получения информации о банке, в котором открыт счет.
//
// Информация о банке требуется при:
//   - Указании банковского счета в счете-фактуре
//   - Регистрации банковских счетов в системе
//   - Выполнении платежей
//   - Учете денежных потоков
//
// Содержит основные идентификационные данные банка, необходимые
// для валидации банковских счетов и проведения платежей.
type Bank struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID - Уникальный идентификатор банка в системе ТУНДУК.
	// Используется для внутренней идентификации банка.
	// Пример: 1, 2, 3 и т.д.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name - Полное наименование банка на русском языке.
	// Официальное название кредитного учреждения.
	// Примеры:
	//   - "Азиатский банк"
	//   - "Кыргызский государственный банк"
	//   - "Универсал Банк"
	//   - "Берёзка Бизнес Банк"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// BIK - Банковский идентификационный код.
	// Уникальный код банка в системе платежей Кыргызской Республики.
	// Присваивается Национальным банком Кыргызской Республики.
	// Используется для маршрутизации платежей и идентификации банка.
	// Формат: обычно 5-6 цифр (например, "110014" для НБКР)
	Bik string `protobuf:"bytes,3,opt,name=bik,proto3" json:"bik,omitempty"`
	// AddressText - Адрес главного офиса банка.
	// Полный почтовый адрес расположения банка или его основного офиса.
	// Используется для справочных целей и контактной информации.
	// Примеры:
	//   - "г. Бишкек, ул. Чуй, 123"
	//   - "720040, Кыргызская Республика, г. Бишкек, ул. Pravdy 96"
	AddressText   string `protobuf:"bytes,4,opt,name=address_text,json=addressText,proto3" json:"address_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank) Reset() {
	*x = Bank{}
	mi := &file_dictionaries_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_dictionaries_bank_proto_rawDescGZIP(), []int{0}
}

func (x *Bank) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetBik() string {
	if x != nil {
		return x.Bik
	}
	return ""
}

func (x *Bank) GetAddressText() string {
	if x != nil {
		return x.AddressText
	}
	return ""
}

var File_dictionaries_bank_proto protoreflect.FileDescriptor

const file_dictionaries_bank_proto_rawDesc = "" +
	"\n" +
	"\x17dictionaries/bank.proto\x12\fdictionaries\"_\n" +
	"\x04Bank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bik\x18\x03 \x01(\tR\x03bik\x12!\n" +
	"\faddress_text\x18\x04 \x01(\tR\vaddressTextB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_bank_proto_rawDescOnce sync.Once
	file_dictionaries_bank_proto_rawDescData []byte
)

func file_dictionaries_bank_proto_rawDescGZIP() []byte {
	file_dictionaries_bank_proto_rawDescOnce.Do(func() {
		file_dictionaries_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_bank_proto_rawDesc), len(file_dictionaries_bank_proto_rawDesc)))
	})
	return file_dictionaries_bank_proto_rawDescData
}

var file_dictionaries_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_bank_proto_goTypes = []any{
	(*Bank)(nil), // 0: dictionaries.Bank
}
var file_dictionaries_bank_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_bank_proto_init() }
func file_dictionaries_bank_proto_init() {
	if File_dictionaries_bank_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_bank_proto_rawDesc), len(file_dictionaries_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_bank_proto_goTypes,
		DependencyIndexes: file_dictionaries_bank_proto_depIdxs,
		MessageInfos:      file_dictionaries_bank_proto_msgTypes,
	}.Build()
	File_dictionaries_bank_proto = out.File
	file_dictionaries_bank_proto_goTypes = nil
	file_dictionaries_bank_proto_depIdxs = nil
}
