// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/bank_account.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BankAccount представляет банковский счет юридического лица.
// Содержит полную информацию о счете, открытом в кредитном учреждении.
//
// Банковские счета используются для:
//   - Указания реквизитов для поступления платежей в счетах-фактурах
//   - Хранения информации о счетах различных контрагентов
//   - Выполнения платежей и переводов
//   - Финансового учета и отчетности
//
// Каждый счет связан с конкретным банком и валютой,
// и может быть отмечен как активный или неиспользуемый.
type BankAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID - Уникальный идентификатор банковского счета в системе ТУНДУК.
	// Используется для ссылки на счет из других таблиц и документов.
	// Пример: 1, 2, 3 и т.д.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// AccountName - Название/описание банковского счета.
	// Условное название для идентификации счета внутри организации.
	// Может отличаться от номера счета и служить для удобства пользователя.
	// Примеры:
	//   - "Основной расчетный счет"
	//   - "Счет для зарплаты сотрудников"
	//   - "Счет для поступления от покупателей"
	//   - "Валютный счет в USD"
	AccountName string `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// BankAccount - Номер банковского счета.
	// Полный номер счета, открытого в банке.
	// Уникально идентифицирует счет в банке.
	// Используется для отправки платежей и финансовых операций.
	// Формат: обычно 20-24 цифры (в зависимости от страны и банка)
	// Примеры: "0012000012345678901234", "KG0123 KGBK 0000 0001"
	BankAccount string `protobuf:"bytes,3,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	// ContractorTIN - ИНН (Персональный идентификационный номер) контрагента.
	// Идентификатор организации/физического лица, владельца этого счета.
	// Используется для связи счета с его владельцем.
	// Формат: 14 цифр (например, "12345678901234")
	// Если счет принадлежит текущей организации, это может быть ее ИНН.
	// Если счет партнера/контрагента, это его ИНН.
	ContractorTin string `protobuf:"bytes,4,opt,name=contractor_tin,json=contractorTin,proto3" json:"contractor_tin,omitempty"`
	// IsActive - Флаг активности банковского счета.
	// true: счет активен и используется для операций
	// false: счет закрыт или временно не используется
	// Используется для фильтрации доступных счетов при создании документов.
	IsActive bool `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Currency - Валюта счета (KGS, USD, EUR и т.д.).
	// Определяет, в какой валюте открыт счет и проводятся операции.
	// Связан со справочником валют.
	Currency *ReferenceItem `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	// Bank - Информация о банке, в котором открыт счет.
	// Содержит наименование банка, БИК и адрес.
	// Обязательное поле для корректной идентификации банковского счета.
	Bank *Bank `protobuf:"bytes,7,opt,name=bank,proto3" json:"bank,omitempty"`
	// IsResident - Флаг резидентства владельца счета.
	// true: владелец счета является резидентом Кыргызской Республики
	// false: владелец счета является нерезидентом (иностранное лицо)
	// Влияет на применимые налоговые ставки и процедуры.
	IsResident    bool `protobuf:"varint,8,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	mi := &file_dictionaries_bank_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_bank_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_dictionaries_bank_account_proto_rawDescGZIP(), []int{0}
}

func (x *BankAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BankAccount) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BankAccount) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *BankAccount) GetContractorTin() string {
	if x != nil {
		return x.ContractorTin
	}
	return ""
}

func (x *BankAccount) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BankAccount) GetCurrency() *ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *BankAccount) GetBank() *Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *BankAccount) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

var File_dictionaries_bank_account_proto protoreflect.FileDescriptor

const file_dictionaries_bank_account_proto_rawDesc = "" +
	"\n" +
	"\x1fdictionaries/bank_account.proto\x12\fdictionaries\x1a\x17dictionaries/bank.proto\x1a!dictionaries/reference_item.proto\"\xa9\x02\n" +
	"\vBankAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12!\n" +
	"\fbank_account\x18\x03 \x01(\tR\vbankAccount\x12%\n" +
	"\x0econtractor_tin\x18\x04 \x01(\tR\rcontractorTin\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x127\n" +
	"\bcurrency\x18\x06 \x01(\v2\x1b.dictionaries.ReferenceItemR\bcurrency\x12&\n" +
	"\x04bank\x18\a \x01(\v2\x12.dictionaries.BankR\x04bank\x12\x1f\n" +
	"\vis_resident\x18\b \x01(\bR\n" +
	"isResidentB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_bank_account_proto_rawDescOnce sync.Once
	file_dictionaries_bank_account_proto_rawDescData []byte
)

func file_dictionaries_bank_account_proto_rawDescGZIP() []byte {
	file_dictionaries_bank_account_proto_rawDescOnce.Do(func() {
		file_dictionaries_bank_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_bank_account_proto_rawDesc), len(file_dictionaries_bank_account_proto_rawDesc)))
	})
	return file_dictionaries_bank_account_proto_rawDescData
}

var file_dictionaries_bank_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_bank_account_proto_goTypes = []any{
	(*BankAccount)(nil),   // 0: dictionaries.BankAccount
	(*ReferenceItem)(nil), // 1: dictionaries.ReferenceItem
	(*Bank)(nil),          // 2: dictionaries.Bank
}
var file_dictionaries_bank_account_proto_depIdxs = []int32{
	1, // 0: dictionaries.BankAccount.currency:type_name -> dictionaries.ReferenceItem
	2, // 1: dictionaries.BankAccount.bank:type_name -> dictionaries.Bank
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dictionaries_bank_account_proto_init() }
func file_dictionaries_bank_account_proto_init() {
	if File_dictionaries_bank_account_proto != nil {
		return
	}
	file_dictionaries_bank_proto_init()
	file_dictionaries_reference_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_bank_account_proto_rawDesc), len(file_dictionaries_bank_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_bank_account_proto_goTypes,
		DependencyIndexes: file_dictionaries_bank_account_proto_depIdxs,
		MessageInfos:      file_dictionaries_bank_account_proto_msgTypes,
	}.Build()
	File_dictionaries_bank_account_proto = out.File
	file_dictionaries_bank_account_proto_goTypes = nil
	file_dictionaries_bank_account_proto_depIdxs = nil
}
