// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/catalog.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalog представляет справочник товаров/услуг организации.
// Это внутренний справочник каждой организации, содержащий перечень
// товаров и услуг, которые она производит, продает или покупает.
//
// Использование каталога:
//   - Стандартизация описания товаров/услуг при создании счетов
//   - Быстрое заполнение счетов выбором из справочника
//   - Ведение истории товаров, которые продавались/покупались
//   - Управление классификацией и кодировкой товаров
//
// Каталог облегчает работу с документами и обеспечивает единообразие
// в описании товаров/услуг в различных счетах и договорах.
type Catalog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID - Уникальный идентификатор записи в справочнике.
	// Используется для ссылки на этот товар/услугу из счетов и других документов.
	// Пример: 1, 2, 3 и т.д.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name - Полное наименование товара или оказываемой услуги.
	// Описание товара, как оно должно появляться в счетах-фактурах.
	// Должно быть четким, полным и недвусмысленным.
	// Примеры:
	//   - "Портативный компьютер ASUS VivoBook 15 (процессор Intel i7)"
	//   - "Услуга дизайна веб-сайта (от 40 до 80 часов работы)"
	//   - "Услуга консультирования по налоговому праву (1 час)"
	//   - "Кабель сетевой UTP категория 6, метр"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Number - Внутренний номер товара в справочнике организации.
	// Уникальный идентификатор товара в системе организации.
	// Может использоваться для быстрого поиска и идентификации.
	// Формат зависит от внутренней политики организации.
	// Примеры: "T001", "SKU-12345", "GOOD-2024-001"
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// TNVEDCode - Код товара по ТНВЭД (Таможенная номенклатура внешнеэкономической деятельности).
	// Используется для таможенной классификации товара при импорте/экспорте.
	// Определяет применяемые таможенные пошлины, налоги и льготы.
	// Формат: 10 цифр (например, "8471.30.90")
	// Заполняется в основном для товаров, которые ввозятся/вывозятся.
	// Для услуг и отечественных товаров может быть пусто.
	TnvedCode string `protobuf:"bytes,4,opt,name=tnved_code,json=tnvedCode,proto3" json:"tnved_code,omitempty"`
	// GKEDCode - Код ГКЭД (Государственный классификатор видов экономической деятельности).
	// Используется для классификации товара/услуги по виду экономической деятельности.
	// Определяет отраслевую принадлежность и применяемые налоговые режимы.
	// Может быть пусто для некоторых товаров.
	GkedCode string `protobuf:"bytes,5,opt,name=gked_code,json=gkedCode,proto3" json:"gked_code,omitempty"`
	// UnitClassification - Единица измерения товара/услуги.
	// Определяет, в каких единицах измеряется количество товара.
	// Примеры: "PCS" (штук), "KG" (килограмм), "M" (метр), "HOUR" (часов)
	// Обязательное поле, используется при создании строк счета.
	UnitClassification *ReferenceItem `protobuf:"bytes,6,opt,name=unit_classification,json=unitClassification,proto3" json:"unit_classification,omitempty"`
	// CatalogType - Тип элемента справочника (товар или услуга).
	// Различение между материальными товарами и нематериальными услугами.
	// Примеры кодов: "GOODS" (товар), "SERVICE" (услуга)
	// Влияет на применимость налогов и способ отражения в учете.
	CatalogType   *ReferenceItem `protobuf:"bytes,7,opt,name=catalog_type,json=catalogType,proto3" json:"catalog_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_dictionaries_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_dictionaries_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Catalog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Catalog) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Catalog) GetTnvedCode() string {
	if x != nil {
		return x.TnvedCode
	}
	return ""
}

func (x *Catalog) GetGkedCode() string {
	if x != nil {
		return x.GkedCode
	}
	return ""
}

func (x *Catalog) GetUnitClassification() *ReferenceItem {
	if x != nil {
		return x.UnitClassification
	}
	return nil
}

func (x *Catalog) GetCatalogType() *ReferenceItem {
	if x != nil {
		return x.CatalogType
	}
	return nil
}

var File_dictionaries_catalog_proto protoreflect.FileDescriptor

const file_dictionaries_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1adictionaries/catalog.proto\x12\fdictionaries\x1a!dictionaries/reference_item.proto\"\x8f\x02\n" +
	"\aCatalog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x1d\n" +
	"\n" +
	"tnved_code\x18\x04 \x01(\tR\ttnvedCode\x12\x1b\n" +
	"\tgked_code\x18\x05 \x01(\tR\bgkedCode\x12L\n" +
	"\x13unit_classification\x18\x06 \x01(\v2\x1b.dictionaries.ReferenceItemR\x12unitClassification\x12>\n" +
	"\fcatalog_type\x18\a \x01(\v2\x1b.dictionaries.ReferenceItemR\vcatalogTypeB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_catalog_proto_rawDescOnce sync.Once
	file_dictionaries_catalog_proto_rawDescData []byte
)

func file_dictionaries_catalog_proto_rawDescGZIP() []byte {
	file_dictionaries_catalog_proto_rawDescOnce.Do(func() {
		file_dictionaries_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_catalog_proto_rawDesc), len(file_dictionaries_catalog_proto_rawDesc)))
	})
	return file_dictionaries_catalog_proto_rawDescData
}

var file_dictionaries_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_catalog_proto_goTypes = []any{
	(*Catalog)(nil),       // 0: dictionaries.Catalog
	(*ReferenceItem)(nil), // 1: dictionaries.ReferenceItem
}
var file_dictionaries_catalog_proto_depIdxs = []int32{
	1, // 0: dictionaries.Catalog.unit_classification:type_name -> dictionaries.ReferenceItem
	1, // 1: dictionaries.Catalog.catalog_type:type_name -> dictionaries.ReferenceItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dictionaries_catalog_proto_init() }
func file_dictionaries_catalog_proto_init() {
	if File_dictionaries_catalog_proto != nil {
		return
	}
	file_dictionaries_reference_item_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_catalog_proto_rawDesc), len(file_dictionaries_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_catalog_proto_goTypes,
		DependencyIndexes: file_dictionaries_catalog_proto_depIdxs,
		MessageInfos:      file_dictionaries_catalog_proto_msgTypes,
	}.Build()
	File_dictionaries_catalog_proto = out.File
	file_dictionaries_catalog_proto_goTypes = nil
	file_dictionaries_catalog_proto_depIdxs = nil
}
