// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/country.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Country представляет страну с кодом и названием.
//
// Используется для указания страны происхождения товаров,
// страны регистрации контрагента или странах доставки.
// Коды стран соответствуют международному стандарту ISO 3166-1 alpha-3
// или другим классификаторам, используемым в Кыргызской Республике.
//
// Примеры:
//   - код="KGZ", название="Кыргызская Республика"
//   - код="RUS", название="Россия"
//   - код="KAZ", название="Казахстан"
//   - код="UZB", название="Узбекистан"
//   - код="CHN", название="Китайская Народная Республика"
type Country struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code - Код страны по международному классификатору.
	// Обычно используется 3-символьный код ISO 3166-1 alpha-3,
	// но может быть использован другой формат в зависимости от
	// требований системы ТУНДУК.
	// Примеры: "KGZ", "RUS", "KAZ", "UZB", "CHN"
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Name - Полное наименование страны на русском языке.
	// Используется для отображения пользователю и в документах.
	// Примеры: "Кыргызская Республика", "Россия", "Казахстан"
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_dictionaries_country_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_country_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_dictionaries_country_proto_rawDescGZIP(), []int{0}
}

func (x *Country) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dictionaries_country_proto protoreflect.FileDescriptor

const file_dictionaries_country_proto_rawDesc = "" +
	"\n" +
	"\x1adictionaries/country.proto\x12\fdictionaries\"1\n" +
	"\aCountry\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_country_proto_rawDescOnce sync.Once
	file_dictionaries_country_proto_rawDescData []byte
)

func file_dictionaries_country_proto_rawDescGZIP() []byte {
	file_dictionaries_country_proto_rawDescOnce.Do(func() {
		file_dictionaries_country_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_country_proto_rawDesc), len(file_dictionaries_country_proto_rawDesc)))
	})
	return file_dictionaries_country_proto_rawDescData
}

var file_dictionaries_country_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_country_proto_goTypes = []any{
	(*Country)(nil), // 0: dictionaries.Country
}
var file_dictionaries_country_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_country_proto_init() }
func file_dictionaries_country_proto_init() {
	if File_dictionaries_country_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_country_proto_rawDesc), len(file_dictionaries_country_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_country_proto_goTypes,
		DependencyIndexes: file_dictionaries_country_proto_depIdxs,
		MessageInfos:      file_dictionaries_country_proto_msgTypes,
	}.Build()
	File_dictionaries_country_proto = out.File
	file_dictionaries_country_proto_goTypes = nil
	file_dictionaries_country_proto_depIdxs = nil
}
