// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/foreign_company.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForeignCompany представляет иностранную компанию или иностранного контрагента.
// Используется для хранения информации об иностранных партнерах,
// с которыми организация осуществляет внешнеэкономическую деятельность.
//
// Отличие от обычного Party (юридического лица):
//   - Party используется для резидентов Кыргызской Республики с ИНН
//   - ForeignCompany используется для нерезидентов (иностранных компаний)
//
// Использование:
//   - Экспорт товаров иностранным покупателям
//   - Импорт товаров от иностранных поставщиков
//   - Оказание услуг иностранными компаниями
//   - Управление контрагентами из-за границы
//
// Содержит основные реквизиты иностранной компании, достаточные
// для идентификации и проведения трансграничных операций.
type ForeignCompany struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID - Уникальный идентификатор иностранной компании в системе ТУНДУК.
	// Используется для ссылки на компанию из счетов и других документов.
	// Пример: 1, 2, 3 и т.д.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// PIN - Идентификационный номер иностранной компании.
	// В разных странах это может быть:
	//   - Tax ID / TIN (Tax Identification Number) - Налоговый номер
	//   - VAT Number - Номер по НДС (для стран ЕС)
	//   - Registration Number - Номер регистрации
	//   - Business Number - Бизнес номер
	//   - UN/DUNS Number - Международный номер
	//
	// Используется для идентификации компании в налоговой системе страны происхождения.
	// Может быть пусто, если компания не имеет налогового номера в своей стране.
	// Примеры: "DE123456789", "FR12345678901", "IT12345678901"
	Pin string `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	// FullName - Полное наименование иностранной компании на языке оригинала.
	// Официальное зарегистрированное название компании.
	// Обычно указывается на английском языке или языке страны происхождения.
	// Примеры:
	//   - "Apple Inc."
	//   - "Microsoft Corporation"
	//   - "Samsung Electronics Co., Ltd."
	//   - "Siemens AG"
	//
	// Если название очень длинное, может быть сокращено в пределах разумного.
	FullName      string `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignCompany) Reset() {
	*x = ForeignCompany{}
	mi := &file_dictionaries_foreign_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignCompany) ProtoMessage() {}

func (x *ForeignCompany) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_foreign_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignCompany.ProtoReflect.Descriptor instead.
func (*ForeignCompany) Descriptor() ([]byte, []int) {
	return file_dictionaries_foreign_company_proto_rawDescGZIP(), []int{0}
}

func (x *ForeignCompany) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForeignCompany) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *ForeignCompany) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_dictionaries_foreign_company_proto protoreflect.FileDescriptor

const file_dictionaries_foreign_company_proto_rawDesc = "" +
	"\n" +
	"\"dictionaries/foreign_company.proto\x12\fdictionaries\"O\n" +
	"\x0eForeignCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullNameB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_foreign_company_proto_rawDescOnce sync.Once
	file_dictionaries_foreign_company_proto_rawDescData []byte
)

func file_dictionaries_foreign_company_proto_rawDescGZIP() []byte {
	file_dictionaries_foreign_company_proto_rawDescOnce.Do(func() {
		file_dictionaries_foreign_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_foreign_company_proto_rawDesc), len(file_dictionaries_foreign_company_proto_rawDesc)))
	})
	return file_dictionaries_foreign_company_proto_rawDescData
}

var file_dictionaries_foreign_company_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_foreign_company_proto_goTypes = []any{
	(*ForeignCompany)(nil), // 0: dictionaries.ForeignCompany
}
var file_dictionaries_foreign_company_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_foreign_company_proto_init() }
func file_dictionaries_foreign_company_proto_init() {
	if File_dictionaries_foreign_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_foreign_company_proto_rawDesc), len(file_dictionaries_foreign_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_foreign_company_proto_goTypes,
		DependencyIndexes: file_dictionaries_foreign_company_proto_depIdxs,
		MessageInfos:      file_dictionaries_foreign_company_proto_msgTypes,
	}.Build()
	File_dictionaries_foreign_company_proto = out.File
	file_dictionaries_foreign_company_proto_goTypes = nil
	file_dictionaries_foreign_company_proto_depIdxs = nil
}
