// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/reference_item.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReferenceItem представляет справочный элемент с кодом и названием.
// Это универсальный тип, используемый для всех справочников в ESF API.
//
// Примеры использования:
//   - Валюта: code="KGS", name="Сом"
//   - Статус документа: code="DRAFT", name="Черновик"
//   - Тип оплаты: code="CASH", name="Наличная"
//   - Вид поставки: code="BY_TRANSPORT", name="Доставка транспортом"
type ReferenceItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code - Код справочного элемента.
	// Уникально идентифицирует значение в справочнике.
	// Примеры: "KGS" для сома, "RUB" для рубля, "DRAFT" для черновика
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Name - Наименование справочного элемента.
	// Читаемое описание кода, используется для отображения пользователю.
	// Примеры: "Сом", "Рубль", "Черновик"
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceItem) Reset() {
	*x = ReferenceItem{}
	mi := &file_dictionaries_reference_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceItem) ProtoMessage() {}

func (x *ReferenceItem) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_reference_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceItem.ProtoReflect.Descriptor instead.
func (*ReferenceItem) Descriptor() ([]byte, []int) {
	return file_dictionaries_reference_item_proto_rawDescGZIP(), []int{0}
}

func (x *ReferenceItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReferenceItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dictionaries_reference_item_proto protoreflect.FileDescriptor

const file_dictionaries_reference_item_proto_rawDesc = "" +
	"\n" +
	"!dictionaries/reference_item.proto\x12\fdictionaries\"7\n" +
	"\rReferenceItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_reference_item_proto_rawDescOnce sync.Once
	file_dictionaries_reference_item_proto_rawDescData []byte
)

func file_dictionaries_reference_item_proto_rawDescGZIP() []byte {
	file_dictionaries_reference_item_proto_rawDescOnce.Do(func() {
		file_dictionaries_reference_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_reference_item_proto_rawDesc), len(file_dictionaries_reference_item_proto_rawDesc)))
	})
	return file_dictionaries_reference_item_proto_rawDescData
}

var file_dictionaries_reference_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_reference_item_proto_goTypes = []any{
	(*ReferenceItem)(nil), // 0: dictionaries.ReferenceItem
}
var file_dictionaries_reference_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_reference_item_proto_init() }
func file_dictionaries_reference_item_proto_init() {
	if File_dictionaries_reference_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_reference_item_proto_rawDesc), len(file_dictionaries_reference_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_reference_item_proto_goTypes,
		DependencyIndexes: file_dictionaries_reference_item_proto_depIdxs,
		MessageInfos:      file_dictionaries_reference_item_proto_msgTypes,
	}.Build()
	File_dictionaries_reference_item_proto = out.File
	file_dictionaries_reference_item_proto_goTypes = nil
	file_dictionaries_reference_item_proto_depIdxs = nil
}
