// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dictionaries/vat_tax_type.proto

package dictionaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VATTaxType представляет вид налога НДС (налог на добавленную стоимость)
// с информацией о ставке и названии налога.
//
// Используется для указания налоговой ставки в счетах-фактурах.
// В Кыргызстане могут применяться различные ставки НДС в зависимости
// от типа товаров, услуг и условий поставки.
//
// Примеры:
//   - Стандартная ставка: rate="12%", name="НДС 12%"
//   - Льготная ставка: rate="0%", name="НДС не применяется"
//   - Повышенная ставка: rate="15%", name="НДС 15%"
type VATTaxType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rate - Налоговая ставка НДС в процентах.
	// Строковое представление позволяет точно сохранить значение
	// без потери точности при вычислениях с целыми числами.
	// Примеры: "12%", "0%", "10%", "15%"
	Rate string `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	// Name - Наименование налога.
	// Описание применяемой ставки НДС, используется для отображения
	// пользователю и документах.
	// Примеры: "НДС 12%", "НДС 0% (не применяется)", "НДС 15% (повышенная)"
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VATTaxType) Reset() {
	*x = VATTaxType{}
	mi := &file_dictionaries_vat_tax_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VATTaxType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VATTaxType) ProtoMessage() {}

func (x *VATTaxType) ProtoReflect() protoreflect.Message {
	mi := &file_dictionaries_vat_tax_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VATTaxType.ProtoReflect.Descriptor instead.
func (*VATTaxType) Descriptor() ([]byte, []int) {
	return file_dictionaries_vat_tax_type_proto_rawDescGZIP(), []int{0}
}

func (x *VATTaxType) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *VATTaxType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dictionaries_vat_tax_type_proto protoreflect.FileDescriptor

const file_dictionaries_vat_tax_type_proto_rawDesc = "" +
	"\n" +
	"\x1fdictionaries/vat_tax_type.proto\x12\fdictionaries\"4\n" +
	"\n" +
	"VATTaxType\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\tR\x04rate\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB<Z:github.com/rusgainew/tunduck-app-mk/proto-lib/dictionariesb\x06proto3"

var (
	file_dictionaries_vat_tax_type_proto_rawDescOnce sync.Once
	file_dictionaries_vat_tax_type_proto_rawDescData []byte
)

func file_dictionaries_vat_tax_type_proto_rawDescGZIP() []byte {
	file_dictionaries_vat_tax_type_proto_rawDescOnce.Do(func() {
		file_dictionaries_vat_tax_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionaries_vat_tax_type_proto_rawDesc), len(file_dictionaries_vat_tax_type_proto_rawDesc)))
	})
	return file_dictionaries_vat_tax_type_proto_rawDescData
}

var file_dictionaries_vat_tax_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionaries_vat_tax_type_proto_goTypes = []any{
	(*VATTaxType)(nil), // 0: dictionaries.VATTaxType
}
var file_dictionaries_vat_tax_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionaries_vat_tax_type_proto_init() }
func file_dictionaries_vat_tax_type_proto_init() {
	if File_dictionaries_vat_tax_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionaries_vat_tax_type_proto_rawDesc), len(file_dictionaries_vat_tax_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionaries_vat_tax_type_proto_goTypes,
		DependencyIndexes: file_dictionaries_vat_tax_type_proto_depIdxs,
		MessageInfos:      file_dictionaries_vat_tax_type_proto_msgTypes,
	}.Build()
	File_dictionaries_vat_tax_type_proto = out.File
	file_dictionaries_vat_tax_type_proto_goTypes = nil
	file_dictionaries_vat_tax_type_proto_depIdxs = nil
}
