// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: entities/invoice_financial.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FinancialData содержит все финансовые данные счета-фактуры.
// Используется для группировки и упрощения работы с финансовыми операциями.
type FinancialData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TotalAmount - Общая сумма счета-фактуры.
	// Включает все суммы: базовую стоимость, НДС, НСП и другие налоги.
	TotalAmount float64 `protobuf:"fixed64,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// Данные для специальных документов (авансовые платежи, кредиты и т.д.)
	OpeningBalances             float64 `protobuf:"fixed64,2,opt,name=opening_balances,json=openingBalances,proto3" json:"opening_balances,omitempty"`                                       // Сальдо на начало периода
	AssessedContributionsAmount float64 `protobuf:"fixed64,3,opt,name=assessed_contributions_amount,json=assessedContributionsAmount,proto3" json:"assessed_contributions_amount,omitempty"` // Сумма начисленных взносов
	PaidAmount                  float64 `protobuf:"fixed64,4,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`                                                      // Сумма оплаченная/перечисленная
	PenaltiesAmount             float64 `protobuf:"fixed64,5,opt,name=penalties_amount,json=penaltiesAmount,proto3" json:"penalties_amount,omitempty"`                                       // Сумма штрафов
	FinesAmount                 float64 `protobuf:"fixed64,6,opt,name=fines_amount,json=finesAmount,proto3" json:"fines_amount,omitempty"`                                                   // Сумма пени (процентные штрафы)
	ClosingBalances             float64 `protobuf:"fixed64,7,opt,name=closing_balances,json=closingBalances,proto3" json:"closing_balances,omitempty"`                                       // Сальдо на конец периода
	AmountToBePaid              float64 `protobuf:"fixed64,8,opt,name=amount_to_be_paid,json=amountToBePaid,proto3" json:"amount_to_be_paid,omitempty"`                                      // Сумма к оплате/перечислению
	PersonalAccountNumber       string  `protobuf:"bytes,9,opt,name=personal_account_number,json=personalAccountNumber,proto3" json:"personal_account_number,omitempty"`                     // Номер личного счета налогоплательщика
	// Банковские реквизиты
	LegalPersonBankAccount string `protobuf:"bytes,10,opt,name=legal_person_bank_account,json=legalPersonBankAccount,proto3" json:"legal_person_bank_account,omitempty"` // Счет поставщика/продавца
	ContractorBankAccount  string `protobuf:"bytes,11,opt,name=contractor_bank_account,json=contractorBankAccount,proto3" json:"contractor_bank_account,omitempty"`      // Счет покупателя/контрагента
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FinancialData) Reset() {
	*x = FinancialData{}
	mi := &file_entities_invoice_financial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialData) ProtoMessage() {}

func (x *FinancialData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_invoice_financial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialData.ProtoReflect.Descriptor instead.
func (*FinancialData) Descriptor() ([]byte, []int) {
	return file_entities_invoice_financial_proto_rawDescGZIP(), []int{0}
}

func (x *FinancialData) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *FinancialData) GetOpeningBalances() float64 {
	if x != nil {
		return x.OpeningBalances
	}
	return 0
}

func (x *FinancialData) GetAssessedContributionsAmount() float64 {
	if x != nil {
		return x.AssessedContributionsAmount
	}
	return 0
}

func (x *FinancialData) GetPaidAmount() float64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *FinancialData) GetPenaltiesAmount() float64 {
	if x != nil {
		return x.PenaltiesAmount
	}
	return 0
}

func (x *FinancialData) GetFinesAmount() float64 {
	if x != nil {
		return x.FinesAmount
	}
	return 0
}

func (x *FinancialData) GetClosingBalances() float64 {
	if x != nil {
		return x.ClosingBalances
	}
	return 0
}

func (x *FinancialData) GetAmountToBePaid() float64 {
	if x != nil {
		return x.AmountToBePaid
	}
	return 0
}

func (x *FinancialData) GetPersonalAccountNumber() string {
	if x != nil {
		return x.PersonalAccountNumber
	}
	return ""
}

func (x *FinancialData) GetLegalPersonBankAccount() string {
	if x != nil {
		return x.LegalPersonBankAccount
	}
	return ""
}

func (x *FinancialData) GetContractorBankAccount() string {
	if x != nil {
		return x.ContractorBankAccount
	}
	return ""
}

var File_entities_invoice_financial_proto protoreflect.FileDescriptor

const file_entities_invoice_financial_proto_rawDesc = "" +
	"\n" +
	" entities/invoice_financial.proto\x12\bentities\"\x91\x04\n" +
	"\rFinancialData\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x01R\vtotalAmount\x12)\n" +
	"\x10opening_balances\x18\x02 \x01(\x01R\x0fopeningBalances\x12B\n" +
	"\x1dassessed_contributions_amount\x18\x03 \x01(\x01R\x1bassessedContributionsAmount\x12\x1f\n" +
	"\vpaid_amount\x18\x04 \x01(\x01R\n" +
	"paidAmount\x12)\n" +
	"\x10penalties_amount\x18\x05 \x01(\x01R\x0fpenaltiesAmount\x12!\n" +
	"\ffines_amount\x18\x06 \x01(\x01R\vfinesAmount\x12)\n" +
	"\x10closing_balances\x18\a \x01(\x01R\x0fclosingBalances\x12)\n" +
	"\x11amount_to_be_paid\x18\b \x01(\x01R\x0eamountToBePaid\x126\n" +
	"\x17personal_account_number\x18\t \x01(\tR\x15personalAccountNumber\x129\n" +
	"\x19legal_person_bank_account\x18\n" +
	" \x01(\tR\x16legalPersonBankAccount\x126\n" +
	"\x17contractor_bank_account\x18\v \x01(\tR\x15contractorBankAccountB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/entitiesb\x06proto3"

var (
	file_entities_invoice_financial_proto_rawDescOnce sync.Once
	file_entities_invoice_financial_proto_rawDescData []byte
)

func file_entities_invoice_financial_proto_rawDescGZIP() []byte {
	file_entities_invoice_financial_proto_rawDescOnce.Do(func() {
		file_entities_invoice_financial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_invoice_financial_proto_rawDesc), len(file_entities_invoice_financial_proto_rawDesc)))
	})
	return file_entities_invoice_financial_proto_rawDescData
}

var file_entities_invoice_financial_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_invoice_financial_proto_goTypes = []any{
	(*FinancialData)(nil), // 0: entities.FinancialData
}
var file_entities_invoice_financial_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_invoice_financial_proto_init() }
func file_entities_invoice_financial_proto_init() {
	if File_entities_invoice_financial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_invoice_financial_proto_rawDesc), len(file_entities_invoice_financial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_invoice_financial_proto_goTypes,
		DependencyIndexes: file_entities_invoice_financial_proto_depIdxs,
		MessageInfos:      file_entities_invoice_financial_proto_msgTypes,
	}.Build()
	File_entities_invoice_financial_proto = out.File
	file_entities_invoice_financial_proto_goTypes = nil
	file_entities_invoice_financial_proto_depIdxs = nil
}
