// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: entities/invoice.proto

package entities

import (
	dictionaries "github.com/rusgainew/tunduck-app-mk/proto-lib/dictionaries"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Invoice представляет счет-фактуру (налоговый документ).
// Основной документ в системе электронных счетов-фактур (ЭСФ) ТУНДУК.
//
// Существует три типа счетов-фактур:
//  1. Счет-фактура на реализацию (СФ-РЕ): Поставка товаров/услуг продавцом покупателю
//  2. Счет-фактура на приобретение (СФ-ПР): Получение товаров/услуг покупателем
//  3. Корректировочный счет-фактура (КСФ): Уточнение ошибок в предыдущих счетах
//
// Счет-фактура содержит полную информацию о товарах/услугах, сторонах сделки,
// налогах, платежах и других реквизитах, необходимых для ведения учета
// в соответствии с законодательством Кыргызской Республики.
//
// Жизненный цикл документа:
//
//	Черновик → Отправлено → Одобрено/Отклонено → Подписано → (опционально: Отозвано)
type Invoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DocumentUUID - Уникальный универсальный идентификатор документа.
	// Генерируется системой при создании документа и остается неизменным
	// на протяжении всего жизненного цикла документа.
	// Используется для однозначной идентификации в системе ТУНДУК.
	// Формат: UUID (например, "550e8400-e29b-41d4-a716-446655440000")
	DocumentUuid string `protobuf:"bytes,1,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	// InvoiceNumber - Номер счета-фактуры.
	// Порядковый номер документа, присваиваемый поставщиком/продавцом.
	// Может быть в формате "СФ-001", "001-2024", и т.д., в зависимости от
	// внутренней нумерации организации.
	InvoiceNumber string `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	// Number - Дополнительный номер или код документа.
	// Может использоваться для внутренней идентификации или связи с
	// другими системами (CRM, ERP и т.д.).
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// CorrectedReceiptUUID - UUID корректируемого документа.
	// Заполняется только для корректировочных счетов (КСФ).
	// Содержит UUID счета, который исправляется/корректируется.
	// Для обычных счетов пусто.
	CorrectedReceiptUuid string `protobuf:"bytes,4,opt,name=corrected_receipt_uuid,json=correctedReceiptUuid,proto3" json:"corrected_receipt_uuid,omitempty"`
	// InvoiceDate - Дата составления счета-фактуры (подписания).
	// Дата, когда документ был подготовлен и подписан.
	// Формат: ISO 8601 (YYYY-MM-DD), например "2024-01-15"
	// Может быть nil, если дата еще не установлена.
	InvoiceDate *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	// CreatedDate - Дата создания документа в системе.
	// Системная дата, когда документ был впервые создан.
	// Обычно совпадает с InvoiceDate или немного позже (время разницы).
	// Формат: ISO 8601 (YYYY-MM-DD), например "2024-01-15"
	CreatedDate *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	// DeliveryDate - Дата фактической поставки товаров/оказания услуг.
	// День, когда товары/услуги были получены покупателем.
	// Может отличаться от InvoiceDate, если есть отсрочка доставки.
	// Формат: ISO 8601 (YYYY-MM-DD), например "2024-01-20"
	// Может быть nil для услуг без физической доставки.
	DeliveryDate *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"`
	// CorrecteReceiptCreationDate - Дата создания корректируемого документа.
	// Для корректировочных счетов содержит дату создания оригинального счета.
	// Для обычных счетов пусто.
	// Формат: ISO 8601 (YYYY-MM-DD)
	CorrectedReceiptCreationDate *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=corrected_receipt_creation_date,json=correctedReceiptCreationDate,proto3" json:"corrected_receipt_creation_date,omitempty"`
	// TotalAmount - Общая сумма счета-фактуры.
	// Включает все суммы: базовую стоимость, НДС, НСП и другие налоги.
	// Выражается в сомах Кыргызской Республики или другой валюте (см. Currency).
	// Пример: 15500.00 (15 500 сомов)
	TotalAmount float64 `protobuf:"fixed64,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	// IsResident - Флаг резидентства юридического лица (продавца).
	// Используется для внутренних операций.
	// Для всех международных операций используйте InternationalData.
	IsResident bool `protobuf:"varint,10,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	// Note - Примечание/комментарий к счету-фактуре.
	// Дополнительная информация, комментарии от поставщика/продавца.
	// Может содержать условия платежа, специальные указания и т.д.
	// Необязательное поле, может быть пусто.
	Note string `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	// OwnedCrmReceiptCode - Код документа в системе CRM поставщика.
	// Используется для связи с внешней CRM/ERP системой.
	// Позволяет отслеживать документы в обеих системах параллельно.
	OwnedCrmReceiptCode string `protobuf:"bytes,12,opt,name=owned_crm_receipt_code,json=ownedCrmReceiptCode,proto3" json:"owned_crm_receipt_code,omitempty"`
	// CorrectedReceiptCode - Номер оригинального счета-фактуры.
	// Для КСФ содержит номер счета, который корректируется.
	// Для обычных счетов пусто.
	CorrectedReceiptCode string `protobuf:"bytes,13,opt,name=corrected_receipt_code,json=correctedReceiptCode,proto3" json:"corrected_receipt_code,omitempty"`
	// CorrectionReasonCode - Код причины корректировки.
	// Классификатор, определяющий причину изменения.
	// Примеры: "PRICE_ERROR" (ошибка в цене), "QUANTITY_ERROR" (ошибка в количестве)
	// Заполняется только для КСФ.
	CorrectionReasonCode string `protobuf:"bytes,14,opt,name=correction_reason_code,json=correctionReasonCode,proto3" json:"correction_reason_code,omitempty"`
	// CorrectionReasonName - Текстовое описание причины корректировки.
	// Человеческое объяснение, почему был создан корректировочный счет.
	// Примеры: "Исправление ошибки в цене товара", "Уточнение количества"
	// Заполняется только для КСФ.
	CorrectionReasonName string `protobuf:"bytes,15,opt,name=correction_reason_name,json=correctionReasonName,proto3" json:"correction_reason_name,omitempty"`
	// IsPriceWithoutTaxes - Флаг, указывает ли базовая цена на исключение налогов.
	// true: базовая цена уже без НДС/НСП (налоги добавляются сверху)
	// false: базовая цена включает все налоги
	// Важно для правильного расчета и отображения стоимости товаров.
	IsPriceWithoutTaxes bool `protobuf:"varint,16,opt,name=is_price_without_taxes,json=isPriceWithoutTaxes,proto3" json:"is_price_without_taxes,omitempty"`
	// IsIndustry - Флаг отнесения товаров/услуг к отраслевым.
	// true: товары/услуги относятся к определенной отрасли (используется спецрежим)
	// false: обычная торговля
	IsIndustry bool `protobuf:"varint,17,opt,name=is_industry,json=isIndustry,proto3" json:"is_industry,omitempty"`
	// FinancialData - Финансовые данные счета-фактуры.
	// Включает суммы, банковские реквизиты и данные для специальных документов.
	FinancialData *FinancialData `protobuf:"bytes,18,opt,name=financial_data,json=financialData,proto3" json:"financial_data,omitempty"`
	// InternationalData - Данные для международных операций.
	// Используется для операций с иностранными партнерами.
	InternationalData *InternationalData `protobuf:"bytes,19,opt,name=international_data,json=internationalData,proto3" json:"international_data,omitempty"`
	// ContractData - Данные контракта/договора.
	// Информация о договоре поставки, на основе которого создан счет.
	ContractData *ContractData `protobuf:"bytes,20,opt,name=contract_data,json=contractData,proto3" json:"contract_data,omitempty"`
	// Справочные объекты
	Status       *dictionaries.ReferenceItem `protobuf:"bytes,33,opt,name=status,proto3" json:"status,omitempty"`
	Currency     *dictionaries.ReferenceItem `protobuf:"bytes,34,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentType  *dictionaries.ReferenceItem `protobuf:"bytes,35,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	ReceiptType  *dictionaries.ReferenceItem `protobuf:"bytes,36,opt,name=receipt_type,json=receiptType,proto3" json:"receipt_type,omitempty"`
	DeliveryType *dictionaries.ReferenceItem `protobuf:"bytes,37,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	VatDelivery  *dictionaries.ReferenceItem `protobuf:"bytes,38,opt,name=vat_delivery,json=vatDelivery,proto3" json:"vat_delivery,omitempty"`
	VatTaxType   *dictionaries.VATTaxType    `protobuf:"bytes,39,opt,name=vat_tax_type,json=vatTaxType,proto3" json:"vat_tax_type,omitempty"`
	// Стороны сделки
	LegalPerson *Party `protobuf:"bytes,40,opt,name=legal_person,json=legalPerson,proto3" json:"legal_person,omitempty"`
	Contractor  *Party `protobuf:"bytes,41,opt,name=contractor,proto3" json:"contractor,omitempty"`
	// Географическая информация
	Country       *dictionaries.Country `protobuf:"bytes,42,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_entities_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_entities_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_entities_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

func (x *Invoice) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *Invoice) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Invoice) GetCorrectedReceiptUuid() string {
	if x != nil {
		return x.CorrectedReceiptUuid
	}
	return ""
}

func (x *Invoice) GetInvoiceDate() *wrapperspb.StringValue {
	if x != nil {
		return x.InvoiceDate
	}
	return nil
}

func (x *Invoice) GetCreatedDate() *wrapperspb.StringValue {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *Invoice) GetDeliveryDate() *wrapperspb.StringValue {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

func (x *Invoice) GetCorrectedReceiptCreationDate() *wrapperspb.StringValue {
	if x != nil {
		return x.CorrectedReceiptCreationDate
	}
	return nil
}

func (x *Invoice) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Invoice) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

func (x *Invoice) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Invoice) GetOwnedCrmReceiptCode() string {
	if x != nil {
		return x.OwnedCrmReceiptCode
	}
	return ""
}

func (x *Invoice) GetCorrectedReceiptCode() string {
	if x != nil {
		return x.CorrectedReceiptCode
	}
	return ""
}

func (x *Invoice) GetCorrectionReasonCode() string {
	if x != nil {
		return x.CorrectionReasonCode
	}
	return ""
}

func (x *Invoice) GetCorrectionReasonName() string {
	if x != nil {
		return x.CorrectionReasonName
	}
	return ""
}

func (x *Invoice) GetIsPriceWithoutTaxes() bool {
	if x != nil {
		return x.IsPriceWithoutTaxes
	}
	return false
}

func (x *Invoice) GetIsIndustry() bool {
	if x != nil {
		return x.IsIndustry
	}
	return false
}

func (x *Invoice) GetFinancialData() *FinancialData {
	if x != nil {
		return x.FinancialData
	}
	return nil
}

func (x *Invoice) GetInternationalData() *InternationalData {
	if x != nil {
		return x.InternationalData
	}
	return nil
}

func (x *Invoice) GetContractData() *ContractData {
	if x != nil {
		return x.ContractData
	}
	return nil
}

func (x *Invoice) GetStatus() *dictionaries.ReferenceItem {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Invoice) GetCurrency() *dictionaries.ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *Invoice) GetPaymentType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.PaymentType
	}
	return nil
}

func (x *Invoice) GetReceiptType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.ReceiptType
	}
	return nil
}

func (x *Invoice) GetDeliveryType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.DeliveryType
	}
	return nil
}

func (x *Invoice) GetVatDelivery() *dictionaries.ReferenceItem {
	if x != nil {
		return x.VatDelivery
	}
	return nil
}

func (x *Invoice) GetVatTaxType() *dictionaries.VATTaxType {
	if x != nil {
		return x.VatTaxType
	}
	return nil
}

func (x *Invoice) GetLegalPerson() *Party {
	if x != nil {
		return x.LegalPerson
	}
	return nil
}

func (x *Invoice) GetContractor() *Party {
	if x != nil {
		return x.Contractor
	}
	return nil
}

func (x *Invoice) GetCountry() *dictionaries.Country {
	if x != nil {
		return x.Country
	}
	return nil
}

var File_entities_invoice_proto protoreflect.FileDescriptor

const file_entities_invoice_proto_rawDesc = "" +
	"\n" +
	"\x16entities/invoice.proto\x12\bentities\x1a\x1egoogle/protobuf/wrappers.proto\x1a!dictionaries/reference_item.proto\x1a\x1fdictionaries/vat_tax_type.proto\x1a\x1adictionaries/country.proto\x1a\x14entities/party.proto\x1a entities/invoice_financial.proto\x1a$entities/invoice_international.proto\x1a\x1fentities/invoice_contract.proto\"\xdd\f\n" +
	"\aInvoice\x12#\n" +
	"\rdocument_uuid\x18\x01 \x01(\tR\fdocumentUuid\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x124\n" +
	"\x16corrected_receipt_uuid\x18\x04 \x01(\tR\x14correctedReceiptUuid\x12?\n" +
	"\finvoice_date\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\vinvoiceDate\x12?\n" +
	"\fcreated_date\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vcreatedDate\x12A\n" +
	"\rdelivery_date\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\fdeliveryDate\x12c\n" +
	"\x1fcorrected_receipt_creation_date\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x1ccorrectedReceiptCreationDate\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x01R\vtotalAmount\x12\x1f\n" +
	"\vis_resident\x18\n" +
	" \x01(\bR\n" +
	"isResident\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x123\n" +
	"\x16owned_crm_receipt_code\x18\f \x01(\tR\x13ownedCrmReceiptCode\x124\n" +
	"\x16corrected_receipt_code\x18\r \x01(\tR\x14correctedReceiptCode\x124\n" +
	"\x16correction_reason_code\x18\x0e \x01(\tR\x14correctionReasonCode\x124\n" +
	"\x16correction_reason_name\x18\x0f \x01(\tR\x14correctionReasonName\x123\n" +
	"\x16is_price_without_taxes\x18\x10 \x01(\bR\x13isPriceWithoutTaxes\x12\x1f\n" +
	"\vis_industry\x18\x11 \x01(\bR\n" +
	"isIndustry\x12>\n" +
	"\x0efinancial_data\x18\x12 \x01(\v2\x17.entities.FinancialDataR\rfinancialData\x12J\n" +
	"\x12international_data\x18\x13 \x01(\v2\x1b.entities.InternationalDataR\x11internationalData\x12;\n" +
	"\rcontract_data\x18\x14 \x01(\v2\x16.entities.ContractDataR\fcontractData\x123\n" +
	"\x06status\x18! \x01(\v2\x1b.dictionaries.ReferenceItemR\x06status\x127\n" +
	"\bcurrency\x18\" \x01(\v2\x1b.dictionaries.ReferenceItemR\bcurrency\x12>\n" +
	"\fpayment_type\x18# \x01(\v2\x1b.dictionaries.ReferenceItemR\vpaymentType\x12>\n" +
	"\freceipt_type\x18$ \x01(\v2\x1b.dictionaries.ReferenceItemR\vreceiptType\x12@\n" +
	"\rdelivery_type\x18% \x01(\v2\x1b.dictionaries.ReferenceItemR\fdeliveryType\x12>\n" +
	"\fvat_delivery\x18& \x01(\v2\x1b.dictionaries.ReferenceItemR\vvatDelivery\x12:\n" +
	"\fvat_tax_type\x18' \x01(\v2\x18.dictionaries.VATTaxTypeR\n" +
	"vatTaxType\x122\n" +
	"\flegal_person\x18( \x01(\v2\x0f.entities.PartyR\vlegalPerson\x12/\n" +
	"\n" +
	"contractor\x18) \x01(\v2\x0f.entities.PartyR\n" +
	"contractor\x12/\n" +
	"\acountry\x18* \x01(\v2\x15.dictionaries.CountryR\acountryB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/entitiesb\x06proto3"

var (
	file_entities_invoice_proto_rawDescOnce sync.Once
	file_entities_invoice_proto_rawDescData []byte
)

func file_entities_invoice_proto_rawDescGZIP() []byte {
	file_entities_invoice_proto_rawDescOnce.Do(func() {
		file_entities_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_invoice_proto_rawDesc), len(file_entities_invoice_proto_rawDesc)))
	})
	return file_entities_invoice_proto_rawDescData
}

var file_entities_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_invoice_proto_goTypes = []any{
	(*Invoice)(nil),                    // 0: entities.Invoice
	(*wrapperspb.StringValue)(nil),     // 1: google.protobuf.StringValue
	(*FinancialData)(nil),              // 2: entities.FinancialData
	(*InternationalData)(nil),          // 3: entities.InternationalData
	(*ContractData)(nil),               // 4: entities.ContractData
	(*dictionaries.ReferenceItem)(nil), // 5: dictionaries.ReferenceItem
	(*dictionaries.VATTaxType)(nil),    // 6: dictionaries.VATTaxType
	(*Party)(nil),                      // 7: entities.Party
	(*dictionaries.Country)(nil),       // 8: dictionaries.Country
}
var file_entities_invoice_proto_depIdxs = []int32{
	1,  // 0: entities.Invoice.invoice_date:type_name -> google.protobuf.StringValue
	1,  // 1: entities.Invoice.created_date:type_name -> google.protobuf.StringValue
	1,  // 2: entities.Invoice.delivery_date:type_name -> google.protobuf.StringValue
	1,  // 3: entities.Invoice.corrected_receipt_creation_date:type_name -> google.protobuf.StringValue
	2,  // 4: entities.Invoice.financial_data:type_name -> entities.FinancialData
	3,  // 5: entities.Invoice.international_data:type_name -> entities.InternationalData
	4,  // 6: entities.Invoice.contract_data:type_name -> entities.ContractData
	5,  // 7: entities.Invoice.status:type_name -> dictionaries.ReferenceItem
	5,  // 8: entities.Invoice.currency:type_name -> dictionaries.ReferenceItem
	5,  // 9: entities.Invoice.payment_type:type_name -> dictionaries.ReferenceItem
	5,  // 10: entities.Invoice.receipt_type:type_name -> dictionaries.ReferenceItem
	5,  // 11: entities.Invoice.delivery_type:type_name -> dictionaries.ReferenceItem
	5,  // 12: entities.Invoice.vat_delivery:type_name -> dictionaries.ReferenceItem
	6,  // 13: entities.Invoice.vat_tax_type:type_name -> dictionaries.VATTaxType
	7,  // 14: entities.Invoice.legal_person:type_name -> entities.Party
	7,  // 15: entities.Invoice.contractor:type_name -> entities.Party
	8,  // 16: entities.Invoice.country:type_name -> dictionaries.Country
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_entities_invoice_proto_init() }
func file_entities_invoice_proto_init() {
	if File_entities_invoice_proto != nil {
		return
	}
	file_entities_party_proto_init()
	file_entities_invoice_financial_proto_init()
	file_entities_invoice_international_proto_init()
	file_entities_invoice_contract_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_invoice_proto_rawDesc), len(file_entities_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_invoice_proto_goTypes,
		DependencyIndexes: file_entities_invoice_proto_depIdxs,
		MessageInfos:      file_entities_invoice_proto_msgTypes,
	}.Build()
	File_entities_invoice_proto = out.File
	file_entities_invoice_proto_goTypes = nil
	file_entities_invoice_proto_depIdxs = nil
}
