// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: entities/invoice_contract.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractData содержит данные контракта/договора для счета-фактуры.
// Используется для привязки счета к исходному договору поставки.
type ContractData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DeliveryContractNumber - Номер договора поставки/контракта.
	// Номер основного договора, на основе которого создается счет.
	DeliveryContractNumber string `protobuf:"bytes,1,opt,name=delivery_contract_number,json=deliveryContractNumber,proto3" json:"delivery_contract_number,omitempty"`
	// DeliveryContractDate - Дата договора поставки.
	// Дата подписания основного договора поставки.
	// Формат: ISO 8601 (YYYY-MM-DD)
	DeliveryContractDate *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=delivery_contract_date,json=deliveryContractDate,proto3" json:"delivery_contract_date,omitempty"`
	// OwnedCrmReceiptCode - Код документа в системе CRM поставщика.
	// Используется для связи с внешней CRM/ERP системой.
	OwnedCrmReceiptCode string `protobuf:"bytes,3,opt,name=owned_crm_receipt_code,json=ownedCrmReceiptCode,proto3" json:"owned_crm_receipt_code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ContractData) Reset() {
	*x = ContractData{}
	mi := &file_entities_invoice_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractData) ProtoMessage() {}

func (x *ContractData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_invoice_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractData.ProtoReflect.Descriptor instead.
func (*ContractData) Descriptor() ([]byte, []int) {
	return file_entities_invoice_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractData) GetDeliveryContractNumber() string {
	if x != nil {
		return x.DeliveryContractNumber
	}
	return ""
}

func (x *ContractData) GetDeliveryContractDate() *wrapperspb.StringValue {
	if x != nil {
		return x.DeliveryContractDate
	}
	return nil
}

func (x *ContractData) GetOwnedCrmReceiptCode() string {
	if x != nil {
		return x.OwnedCrmReceiptCode
	}
	return ""
}

var File_entities_invoice_contract_proto protoreflect.FileDescriptor

const file_entities_invoice_contract_proto_rawDesc = "" +
	"\n" +
	"\x1fentities/invoice_contract.proto\x12\bentities\x1a\x1egoogle/protobuf/wrappers.proto\"\xd1\x01\n" +
	"\fContractData\x128\n" +
	"\x18delivery_contract_number\x18\x01 \x01(\tR\x16deliveryContractNumber\x12R\n" +
	"\x16delivery_contract_date\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x14deliveryContractDate\x123\n" +
	"\x16owned_crm_receipt_code\x18\x03 \x01(\tR\x13ownedCrmReceiptCodeB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/entitiesb\x06proto3"

var (
	file_entities_invoice_contract_proto_rawDescOnce sync.Once
	file_entities_invoice_contract_proto_rawDescData []byte
)

func file_entities_invoice_contract_proto_rawDescGZIP() []byte {
	file_entities_invoice_contract_proto_rawDescOnce.Do(func() {
		file_entities_invoice_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_invoice_contract_proto_rawDesc), len(file_entities_invoice_contract_proto_rawDesc)))
	})
	return file_entities_invoice_contract_proto_rawDescData
}

var file_entities_invoice_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_invoice_contract_proto_goTypes = []any{
	(*ContractData)(nil),           // 0: entities.ContractData
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_entities_invoice_contract_proto_depIdxs = []int32{
	1, // 0: entities.ContractData.delivery_contract_date:type_name -> google.protobuf.StringValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entities_invoice_contract_proto_init() }
func file_entities_invoice_contract_proto_init() {
	if File_entities_invoice_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_invoice_contract_proto_rawDesc), len(file_entities_invoice_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_invoice_contract_proto_goTypes,
		DependencyIndexes: file_entities_invoice_contract_proto_depIdxs,
		MessageInfos:      file_entities_invoice_contract_proto_msgTypes,
	}.Build()
	File_entities_invoice_contract_proto = out.File
	file_entities_invoice_contract_proto_goTypes = nil
	file_entities_invoice_contract_proto_depIdxs = nil
}
