// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: entities/invoice_international.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InternationalData содержит данные для международных операций.
// Используется для операций с иностранными партнерами и таможенных процедур.
type InternationalData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IsResident - Флаг резидентства юридического лица (продавца).
	// true: компания является резидентом Кыргызской Республики
	// false: компания является нерезидентом (иностранная компания)
	IsResident bool `protobuf:"varint,1,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	// ExchangeRate - Курс обмена иностранной валюты к сому.
	// Используется при операциях в иностранной валюте.
	// Пример: 0.0119 (если счет в долларах США)
	ExchangeRate float64 `protobuf:"fixed64,2,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	// ForeignName - Наименование иностранной компании/контрагента.
	// Используется, когда контрагент из-за границы.
	ForeignName string `protobuf:"bytes,3,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	// SellerBranchPIN - ИНН филиала/представительства поставщика.
	// Используется, если поставщик осуществляет деятельность через филиалы.
	SellerBranchPin string `protobuf:"bytes,4,opt,name=seller_branch_pin,json=sellerBranchPin,proto3" json:"seller_branch_pin,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InternationalData) Reset() {
	*x = InternationalData{}
	mi := &file_entities_invoice_international_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternationalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternationalData) ProtoMessage() {}

func (x *InternationalData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_invoice_international_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternationalData.ProtoReflect.Descriptor instead.
func (*InternationalData) Descriptor() ([]byte, []int) {
	return file_entities_invoice_international_proto_rawDescGZIP(), []int{0}
}

func (x *InternationalData) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

func (x *InternationalData) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *InternationalData) GetForeignName() string {
	if x != nil {
		return x.ForeignName
	}
	return ""
}

func (x *InternationalData) GetSellerBranchPin() string {
	if x != nil {
		return x.SellerBranchPin
	}
	return ""
}

var File_entities_invoice_international_proto protoreflect.FileDescriptor

const file_entities_invoice_international_proto_rawDesc = "" +
	"\n" +
	"$entities/invoice_international.proto\x12\bentities\"\xa8\x01\n" +
	"\x11InternationalData\x12\x1f\n" +
	"\vis_resident\x18\x01 \x01(\bR\n" +
	"isResident\x12#\n" +
	"\rexchange_rate\x18\x02 \x01(\x01R\fexchangeRate\x12!\n" +
	"\fforeign_name\x18\x03 \x01(\tR\vforeignName\x12*\n" +
	"\x11seller_branch_pin\x18\x04 \x01(\tR\x0fsellerBranchPinB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/entitiesb\x06proto3"

var (
	file_entities_invoice_international_proto_rawDescOnce sync.Once
	file_entities_invoice_international_proto_rawDescData []byte
)

func file_entities_invoice_international_proto_rawDescGZIP() []byte {
	file_entities_invoice_international_proto_rawDescOnce.Do(func() {
		file_entities_invoice_international_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_invoice_international_proto_rawDesc), len(file_entities_invoice_international_proto_rawDesc)))
	})
	return file_entities_invoice_international_proto_rawDescData
}

var file_entities_invoice_international_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_invoice_international_proto_goTypes = []any{
	(*InternationalData)(nil), // 0: entities.InternationalData
}
var file_entities_invoice_international_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_invoice_international_proto_init() }
func file_entities_invoice_international_proto_init() {
	if File_entities_invoice_international_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_invoice_international_proto_rawDesc), len(file_entities_invoice_international_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_invoice_international_proto_goTypes,
		DependencyIndexes: file_entities_invoice_international_proto_depIdxs,
		MessageInfos:      file_entities_invoice_international_proto_msgTypes,
	}.Build()
	File_entities_invoice_international_proto = out.File
	file_entities_invoice_international_proto_goTypes = nil
	file_entities_invoice_international_proto_depIdxs = nil
}
