// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: entities/party.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Party представляет юридическое лицо или контрагента (партнера)
// в счете-фактуре или другой документации.
//
// Используется для идентификации сторон в финансово-хозяйственных операциях:
//   - Продавец/поставщик (юридическое лицо)
//   - Покупатель/приобретатель (контрагент)
//   - Головная организация и ее филиалы/представительства
//
// Структура содержит основные реквизиты организации, необходимые для
// идентификации и ведения учета по операциям.
//
// Примеры использования:
//   - LegalPerson: Party{PIN: "12345678901", FullName: "ООО Компания", ...}
//   - Contractor: Party{PIN: "98765432109", FullName: "ИП Васильев И.И.", ...}
type Party struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PIN - Персональный идентификационный номер (ИНН/УИН) юридического лица.
	// В Кыргызской Республике это уникальный идентификатор налогоплательщика.
	// Используется для идентификации организации в налоговой системе ТУНДУК.
	// Формат: 14 цифр (например, "12345678901234")
	// Обязательное поле для всех операций.
	Pin string `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	// FullName - Полное наименование юридического лица.
	// Официальное регистрационное название организации на русском языке.
	// Используется в документах и отчетах.
	// Примеры: "Открытое акционерное общество 'Компания'", "Частное предприятие 'Торговля'"
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	// MainFullName - Полное наименование головной организации.
	// Заполняется, если текущая организация является филиалом,
	// представительством или дочерней компанией.
	// Содержит наименование материнской/головной организации.
	// Может быть пусто, если организация является самостоятельным юридическим лицом.
	MainFullName string `protobuf:"bytes,3,opt,name=main_full_name,json=mainFullName,proto3" json:"main_full_name,omitempty"`
	// MainPIN - Персональный идентификационный номер (ИНН/УИН) головной организации.
	// Заполняется, если текущая организация является филиалом или подразделением.
	// Содержит ИНН материнской/головной организации для связывания структур.
	// Может быть пусто, если организация независимая.
	// Формат: 14 цифр (например, "98765432101234")
	MainPin       string `protobuf:"bytes,4,opt,name=main_pin,json=mainPin,proto3" json:"main_pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_entities_party_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_entities_party_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_entities_party_proto_rawDescGZIP(), []int{0}
}

func (x *Party) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *Party) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Party) GetMainFullName() string {
	if x != nil {
		return x.MainFullName
	}
	return ""
}

func (x *Party) GetMainPin() string {
	if x != nil {
		return x.MainPin
	}
	return ""
}

var File_entities_party_proto protoreflect.FileDescriptor

const file_entities_party_proto_rawDesc = "" +
	"\n" +
	"\x14entities/party.proto\x12\bentities\"w\n" +
	"\x05Party\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\tR\x03pin\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12$\n" +
	"\x0emain_full_name\x18\x03 \x01(\tR\fmainFullName\x12\x19\n" +
	"\bmain_pin\x18\x04 \x01(\tR\amainPinB8Z6github.com/rusgainew/tunduck-app-mk/proto-lib/entitiesb\x06proto3"

var (
	file_entities_party_proto_rawDescOnce sync.Once
	file_entities_party_proto_rawDescData []byte
)

func file_entities_party_proto_rawDescGZIP() []byte {
	file_entities_party_proto_rawDescOnce.Do(func() {
		file_entities_party_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_party_proto_rawDesc), len(file_entities_party_proto_rawDesc)))
	})
	return file_entities_party_proto_rawDescData
}

var file_entities_party_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_party_proto_goTypes = []any{
	(*Party)(nil), // 0: entities.Party
}
var file_entities_party_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_party_proto_init() }
func file_entities_party_proto_init() {
	if File_entities_party_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_party_proto_rawDesc), len(file_entities_party_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_party_proto_goTypes,
		DependencyIndexes: file_entities_party_proto_depIdxs,
		MessageInfos:      file_entities_party_proto_msgTypes,
	}.Build()
	File_entities_party_proto = out.File
	file_entities_party_proto_goTypes = nil
	file_entities_party_proto_depIdxs = nil
}
