// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/api_response.proto

package api

import (
	dictionaries "github.com/rusgainew/tunduck-app-mk/proto-lib/dictionaries"
	entities "github.com/rusgainew/tunduck-app-mk/proto-lib/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIResponse представляет базовый обобщенный ответ API.
// Используется как базовая структура для всех endpoints в ESF API.
// Это универсальная структура, которая может содержать различные типы данных.
//
// Структура позволяет:
//   - Унифицировать формат ответов всех API endpoints
//   - Включить общую информацию о запросе/ответе (ID, пользователь, клиент)
//   - Поддерживать пагинацию при необходимости
//   - Возвращать ошибки в стандартном формате
//
// Поле Data используется для хранения основных данных ответа,
// тип которого зависит от конкретного endpoint.
type APIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RequestID - Уникальный идентификатор входящего запроса.
	// Генерируется клиентом и отправляется в каждом запросе.
	// Используется для отслеживания запроса в логах системы.
	// Может быть nil, если клиент не предоставил ID запроса.
	RequestId *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// ResponseID - Уникальный идентификатор ответа.
	// Генерируется сервером при обработке запроса.
	// Может использоваться для поддержки клиентом и связи с сервером.
	ResponseId *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	// UserID - Идентификатор пользователя, от которого пришел запрос.
	// Полезен для аудита и логирования операций.
	// Может быть nil, если информация недоступна.
	UserId *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// ClientID - Идентификатор клиентского приложения или системы.
	// Используется при интеграции с внешними системами через API.
	// Может быть nil.
	ClientId *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// TotalElements - Общее количество элементов во всех страницах.
	// Заполняется только для endpoint'ов, возвращающих списки.
	// Может быть nil для endpoint'ов, возвращающих одиночный объект.
	TotalElements *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	// TotalPage - Общее количество страниц.
	// Заполняется только для endpoint'ов, возвращающих списки с пагинацией.
	// Может быть nil.
	TotalPage *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	// Data - Основной контент ответа.
	// Тип данных зависит от вызываемого endpoint:
	//   - Для одиночных объектов: Invoice, BankAccount, Catalog и т.д.
	//   - Для списков: InvoiceListResponse, BankAccountListResponse и т.д.
	//   - Для операций: результат операции или статус выполнения
	//
	// В protobuf используется oneof для различных типов данных
	//
	// Types that are valid to be assigned to Data:
	//
	//	*APIResponse_Invoice
	//	*APIResponse_InvoiceList
	//	*APIResponse_BankAccount
	//	*APIResponse_BankAccountList
	//	*APIResponse_Catalog
	//	*APIResponse_CatalogList
	Data          isAPIResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_api_api_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_api_api_response_proto_rawDescGZIP(), []int{0}
}

func (x *APIResponse) GetRequestId() *wrapperspb.StringValue {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *APIResponse) GetResponseId() *wrapperspb.StringValue {
	if x != nil {
		return x.ResponseId
	}
	return nil
}

func (x *APIResponse) GetUserId() *wrapperspb.StringValue {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *APIResponse) GetClientId() *wrapperspb.StringValue {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *APIResponse) GetTotalElements() *wrapperspb.Int32Value {
	if x != nil {
		return x.TotalElements
	}
	return nil
}

func (x *APIResponse) GetTotalPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.TotalPage
	}
	return nil
}

func (x *APIResponse) GetData() isAPIResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *APIResponse) GetInvoice() *entities.Invoice {
	if x != nil {
		if x, ok := x.Data.(*APIResponse_Invoice); ok {
			return x.Invoice
		}
	}
	return nil
}

func (x *APIResponse) GetInvoiceList() *InvoiceListResponse {
	if x != nil {
		if x, ok := x.Data.(*APIResponse_InvoiceList); ok {
			return x.InvoiceList
		}
	}
	return nil
}

func (x *APIResponse) GetBankAccount() *dictionaries.BankAccount {
	if x != nil {
		if x, ok := x.Data.(*APIResponse_BankAccount); ok {
			return x.BankAccount
		}
	}
	return nil
}

func (x *APIResponse) GetBankAccountList() *BankAccountListResponse {
	if x != nil {
		if x, ok := x.Data.(*APIResponse_BankAccountList); ok {
			return x.BankAccountList
		}
	}
	return nil
}

func (x *APIResponse) GetCatalog() *dictionaries.Catalog {
	if x != nil {
		if x, ok := x.Data.(*APIResponse_Catalog); ok {
			return x.Catalog
		}
	}
	return nil
}

func (x *APIResponse) GetCatalogList() *CatalogListResponse {
	if x != nil {
		if x, ok := x.Data.(*APIResponse_CatalogList); ok {
			return x.CatalogList
		}
	}
	return nil
}

type isAPIResponse_Data interface {
	isAPIResponse_Data()
}

type APIResponse_Invoice struct {
	Invoice *entities.Invoice `protobuf:"bytes,7,opt,name=invoice,proto3,oneof"`
}

type APIResponse_InvoiceList struct {
	InvoiceList *InvoiceListResponse `protobuf:"bytes,8,opt,name=invoice_list,json=invoiceList,proto3,oneof"`
}

type APIResponse_BankAccount struct {
	BankAccount *dictionaries.BankAccount `protobuf:"bytes,9,opt,name=bank_account,json=bankAccount,proto3,oneof"`
}

type APIResponse_BankAccountList struct {
	BankAccountList *BankAccountListResponse `protobuf:"bytes,10,opt,name=bank_account_list,json=bankAccountList,proto3,oneof"`
}

type APIResponse_Catalog struct {
	Catalog *dictionaries.Catalog `protobuf:"bytes,11,opt,name=catalog,proto3,oneof"`
}

type APIResponse_CatalogList struct {
	CatalogList *CatalogListResponse `protobuf:"bytes,12,opt,name=catalog_list,json=catalogList,proto3,oneof"`
}

func (*APIResponse_Invoice) isAPIResponse_Data() {}

func (*APIResponse_InvoiceList) isAPIResponse_Data() {}

func (*APIResponse_BankAccount) isAPIResponse_Data() {}

func (*APIResponse_BankAccountList) isAPIResponse_Data() {}

func (*APIResponse_Catalog) isAPIResponse_Data() {}

func (*APIResponse_CatalogList) isAPIResponse_Data() {}

// InvoiceListResponse представляет специализированный ответ со списком счетов-фактур.
// Используется для endpoint'ов, возвращающих множество счетов с пагинацией.
type InvoiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page - Номер текущей страницы (отсчет с нуля: 0, 1, 2, ...)
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Size - Количество счетов на текущей странице (максимальный размер страницы)
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// TotalElements - Общее количество счетов, доступных в системе
	// (не только на текущей странице, а все счета целиком)
	TotalElements int32 `protobuf:"varint,3,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	// TotalPage - Общее количество страниц для получения всех счетов
	TotalPage int32 `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	// Invoices - Список счетов-фактур на текущей странице.
	// Максимальное количество элементов определяется параметром size запроса.
	// Каждый элемент содержит полную информацию о счете.
	Invoices      []*entities.Invoice `protobuf:"bytes,5,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceListResponse) Reset() {
	*x = InvoiceListResponse{}
	mi := &file_api_api_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceListResponse) ProtoMessage() {}

func (x *InvoiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceListResponse.ProtoReflect.Descriptor instead.
func (*InvoiceListResponse) Descriptor() ([]byte, []int) {
	return file_api_api_response_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *InvoiceListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InvoiceListResponse) GetTotalElements() int32 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *InvoiceListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *InvoiceListResponse) GetInvoices() []*entities.Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

// DetailListResponse представляет специализированный ответ со списком деталей счета.
// Используется для endpoint'ов, возвращающих строки/позиции счета-фактуры с пагинацией.
type DetailListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Page          int32                     `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                     `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalElements int32                     `protobuf:"varint,3,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	TotalPage     int32                     `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Details       []*entities.InvoiceDetail `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailListResponse) Reset() {
	*x = DetailListResponse{}
	mi := &file_api_api_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailListResponse) ProtoMessage() {}

func (x *DetailListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailListResponse.ProtoReflect.Descriptor instead.
func (*DetailListResponse) Descriptor() ([]byte, []int) {
	return file_api_api_response_proto_rawDescGZIP(), []int{2}
}

func (x *DetailListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DetailListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DetailListResponse) GetTotalElements() int32 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *DetailListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *DetailListResponse) GetDetails() []*entities.InvoiceDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// BankAccountListResponse представляет специализированный ответ со списком банковских счетов.
type BankAccountListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Page          int32                       `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                       `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalElements int32                       `protobuf:"varint,3,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	TotalPage     int32                       `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	BankAccounts  []*dictionaries.BankAccount `protobuf:"bytes,5,rep,name=bank_accounts,json=bankAccounts,proto3" json:"bank_accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccountListResponse) Reset() {
	*x = BankAccountListResponse{}
	mi := &file_api_api_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccountListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccountListResponse) ProtoMessage() {}

func (x *BankAccountListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccountListResponse.ProtoReflect.Descriptor instead.
func (*BankAccountListResponse) Descriptor() ([]byte, []int) {
	return file_api_api_response_proto_rawDescGZIP(), []int{3}
}

func (x *BankAccountListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BankAccountListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BankAccountListResponse) GetTotalElements() int32 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *BankAccountListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *BankAccountListResponse) GetBankAccounts() []*dictionaries.BankAccount {
	if x != nil {
		return x.BankAccounts
	}
	return nil
}

// CatalogListResponse представляет специализированный ответ со списком элементов каталога.
type CatalogListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Page          int32                   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	TotalElements int32                   `protobuf:"varint,3,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	TotalPage     int32                   `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Catalogs      []*dictionaries.Catalog `protobuf:"bytes,5,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogListResponse) Reset() {
	*x = CatalogListResponse{}
	mi := &file_api_api_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogListResponse) ProtoMessage() {}

func (x *CatalogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogListResponse.ProtoReflect.Descriptor instead.
func (*CatalogListResponse) Descriptor() ([]byte, []int) {
	return file_api_api_response_proto_rawDescGZIP(), []int{4}
}

func (x *CatalogListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CatalogListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CatalogListResponse) GetTotalElements() int32 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *CatalogListResponse) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *CatalogListResponse) GetCatalogs() []*dictionaries.Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

var File_api_api_response_proto protoreflect.FileDescriptor

const file_api_api_response_proto_rawDesc = "" +
	"\n" +
	"\x16api/api_response.proto\x12\x03api\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16entities/invoice.proto\x1a\x1dentities/invoice_detail.proto\x1a\x1fdictionaries/bank_account.proto\x1a\x1adictionaries/catalog.proto\"\xef\x05\n" +
	"\vAPIResponse\x12;\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\trequestId\x12=\n" +
	"\vresponse_id\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"responseId\x125\n" +
	"\auser_id\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06userId\x129\n" +
	"\tclient_id\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\bclientId\x12B\n" +
	"\x0etotal_elements\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\rtotalElements\x12:\n" +
	"\n" +
	"total_page\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\ttotalPage\x12-\n" +
	"\ainvoice\x18\a \x01(\v2\x11.entities.InvoiceH\x00R\ainvoice\x12=\n" +
	"\finvoice_list\x18\b \x01(\v2\x18.api.InvoiceListResponseH\x00R\vinvoiceList\x12>\n" +
	"\fbank_account\x18\t \x01(\v2\x19.dictionaries.BankAccountH\x00R\vbankAccount\x12J\n" +
	"\x11bank_account_list\x18\n" +
	" \x01(\v2\x1c.api.BankAccountListResponseH\x00R\x0fbankAccountList\x121\n" +
	"\acatalog\x18\v \x01(\v2\x15.dictionaries.CatalogH\x00R\acatalog\x12=\n" +
	"\fcatalog_list\x18\f \x01(\v2\x18.api.CatalogListResponseH\x00R\vcatalogListB\x06\n" +
	"\x04data\"\xb2\x01\n" +
	"\x13InvoiceListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12%\n" +
	"\x0etotal_elements\x18\x03 \x01(\x05R\rtotalElements\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x05R\ttotalPage\x12-\n" +
	"\binvoices\x18\x05 \x03(\v2\x11.entities.InvoiceR\binvoices\"\xb5\x01\n" +
	"\x12DetailListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12%\n" +
	"\x0etotal_elements\x18\x03 \x01(\x05R\rtotalElements\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x05R\ttotalPage\x121\n" +
	"\adetails\x18\x05 \x03(\v2\x17.entities.InvoiceDetailR\adetails\"\xc7\x01\n" +
	"\x17BankAccountListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12%\n" +
	"\x0etotal_elements\x18\x03 \x01(\x05R\rtotalElements\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x05R\ttotalPage\x12>\n" +
	"\rbank_accounts\x18\x05 \x03(\v2\x19.dictionaries.BankAccountR\fbankAccounts\"\xb6\x01\n" +
	"\x13CatalogListResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12%\n" +
	"\x0etotal_elements\x18\x03 \x01(\x05R\rtotalElements\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x05R\ttotalPage\x121\n" +
	"\bcatalogs\x18\x05 \x03(\v2\x15.dictionaries.CatalogR\bcatalogsB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var (
	file_api_api_response_proto_rawDescOnce sync.Once
	file_api_api_response_proto_rawDescData []byte
)

func file_api_api_response_proto_rawDescGZIP() []byte {
	file_api_api_response_proto_rawDescOnce.Do(func() {
		file_api_api_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_response_proto_rawDesc), len(file_api_api_response_proto_rawDesc)))
	})
	return file_api_api_response_proto_rawDescData
}

var file_api_api_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_api_response_proto_goTypes = []any{
	(*APIResponse)(nil),              // 0: api.APIResponse
	(*InvoiceListResponse)(nil),      // 1: api.InvoiceListResponse
	(*DetailListResponse)(nil),       // 2: api.DetailListResponse
	(*BankAccountListResponse)(nil),  // 3: api.BankAccountListResponse
	(*CatalogListResponse)(nil),      // 4: api.CatalogListResponse
	(*wrapperspb.StringValue)(nil),   // 5: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),    // 6: google.protobuf.Int32Value
	(*entities.Invoice)(nil),         // 7: entities.Invoice
	(*dictionaries.BankAccount)(nil), // 8: dictionaries.BankAccount
	(*dictionaries.Catalog)(nil),     // 9: dictionaries.Catalog
	(*entities.InvoiceDetail)(nil),   // 10: entities.InvoiceDetail
}
var file_api_api_response_proto_depIdxs = []int32{
	5,  // 0: api.APIResponse.request_id:type_name -> google.protobuf.StringValue
	5,  // 1: api.APIResponse.response_id:type_name -> google.protobuf.StringValue
	5,  // 2: api.APIResponse.user_id:type_name -> google.protobuf.StringValue
	5,  // 3: api.APIResponse.client_id:type_name -> google.protobuf.StringValue
	6,  // 4: api.APIResponse.total_elements:type_name -> google.protobuf.Int32Value
	6,  // 5: api.APIResponse.total_page:type_name -> google.protobuf.Int32Value
	7,  // 6: api.APIResponse.invoice:type_name -> entities.Invoice
	1,  // 7: api.APIResponse.invoice_list:type_name -> api.InvoiceListResponse
	8,  // 8: api.APIResponse.bank_account:type_name -> dictionaries.BankAccount
	3,  // 9: api.APIResponse.bank_account_list:type_name -> api.BankAccountListResponse
	9,  // 10: api.APIResponse.catalog:type_name -> dictionaries.Catalog
	4,  // 11: api.APIResponse.catalog_list:type_name -> api.CatalogListResponse
	7,  // 12: api.InvoiceListResponse.invoices:type_name -> entities.Invoice
	10, // 13: api.DetailListResponse.details:type_name -> entities.InvoiceDetail
	8,  // 14: api.BankAccountListResponse.bank_accounts:type_name -> dictionaries.BankAccount
	9,  // 15: api.CatalogListResponse.catalogs:type_name -> dictionaries.Catalog
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_api_response_proto_init() }
func file_api_api_response_proto_init() {
	if File_api_api_response_proto != nil {
		return
	}
	file_api_api_response_proto_msgTypes[0].OneofWrappers = []any{
		(*APIResponse_Invoice)(nil),
		(*APIResponse_InvoiceList)(nil),
		(*APIResponse_BankAccount)(nil),
		(*APIResponse_BankAccountList)(nil),
		(*APIResponse_Catalog)(nil),
		(*APIResponse_CatalogList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_response_proto_rawDesc), len(file_api_api_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_response_proto_goTypes,
		DependencyIndexes: file_api_api_response_proto_depIdxs,
		MessageInfos:      file_api_api_response_proto_msgTypes,
	}.Build()
	File_api_api_response_proto = out.File
	file_api_api_response_proto_goTypes = nil
	file_api_api_response_proto_depIdxs = nil
}
