// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/bank_account_requests.proto

package api

import (
	dictionaries "github.com/rusgainew/tunduck-app-mk/proto-lib/dictionaries"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateBankAccountRequest представляет запрос на создание банковского счета.
// Используется для POST запроса /api/command/legal-person/bank-account/create
type CreateBankAccountRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	AccountName   string                      `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	BankAccount   string                      `protobuf:"bytes,2,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	ContractorTin string                      `protobuf:"bytes,3,opt,name=contractor_tin,json=contractorTin,proto3" json:"contractor_tin,omitempty"`
	Currency      *dictionaries.ReferenceItem `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Bank          *dictionaries.Bank          `protobuf:"bytes,5,opt,name=bank,proto3" json:"bank,omitempty"`
	IsResident    bool                        `protobuf:"varint,6,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankAccountRequest) Reset() {
	*x = CreateBankAccountRequest{}
	mi := &file_api_bank_account_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankAccountRequest) ProtoMessage() {}

func (x *CreateBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bank_account_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_bank_account_requests_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBankAccountRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateBankAccountRequest) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *CreateBankAccountRequest) GetContractorTin() string {
	if x != nil {
		return x.ContractorTin
	}
	return ""
}

func (x *CreateBankAccountRequest) GetCurrency() *dictionaries.ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *CreateBankAccountRequest) GetBank() *dictionaries.Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *CreateBankAccountRequest) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

// UpdateBankAccountRequest представляет запрос на обновление банковского счета.
// Используется для PUT запроса /api/command/legal-person/bank-account/edit/{id}
type UpdateBankAccountRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountName   string                      `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	BankAccount   string                      `protobuf:"bytes,3,opt,name=bank_account,json=bankAccount,proto3" json:"bank_account,omitempty"`
	Currency      *dictionaries.ReferenceItem `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Bank          *dictionaries.Bank          `protobuf:"bytes,5,opt,name=bank,proto3" json:"bank,omitempty"`
	IsResident    bool                        `protobuf:"varint,6,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankAccountRequest) Reset() {
	*x = UpdateBankAccountRequest{}
	mi := &file_api_bank_account_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankAccountRequest) ProtoMessage() {}

func (x *UpdateBankAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bank_account_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateBankAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_bank_account_requests_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBankAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBankAccountRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UpdateBankAccountRequest) GetBankAccount() string {
	if x != nil {
		return x.BankAccount
	}
	return ""
}

func (x *UpdateBankAccountRequest) GetCurrency() *dictionaries.ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *UpdateBankAccountRequest) GetBank() *dictionaries.Bank {
	if x != nil {
		return x.Bank
	}
	return nil
}

func (x *UpdateBankAccountRequest) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

var File_api_bank_account_requests_proto protoreflect.FileDescriptor

const file_api_bank_account_requests_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/bank_account_requests.proto\x12\x03api\x1a!dictionaries/reference_item.proto\x1a\x17dictionaries/bank.proto\"\x89\x02\n" +
	"\x18CreateBankAccountRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\x12!\n" +
	"\fbank_account\x18\x02 \x01(\tR\vbankAccount\x12%\n" +
	"\x0econtractor_tin\x18\x03 \x01(\tR\rcontractorTin\x127\n" +
	"\bcurrency\x18\x04 \x01(\v2\x1b.dictionaries.ReferenceItemR\bcurrency\x12&\n" +
	"\x04bank\x18\x05 \x01(\v2\x12.dictionaries.BankR\x04bank\x12\x1f\n" +
	"\vis_resident\x18\x06 \x01(\bR\n" +
	"isResident\"\xf2\x01\n" +
	"\x18UpdateBankAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12!\n" +
	"\fbank_account\x18\x03 \x01(\tR\vbankAccount\x127\n" +
	"\bcurrency\x18\x04 \x01(\v2\x1b.dictionaries.ReferenceItemR\bcurrency\x12&\n" +
	"\x04bank\x18\x05 \x01(\v2\x12.dictionaries.BankR\x04bank\x12\x1f\n" +
	"\vis_resident\x18\x06 \x01(\bR\n" +
	"isResidentB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var (
	file_api_bank_account_requests_proto_rawDescOnce sync.Once
	file_api_bank_account_requests_proto_rawDescData []byte
)

func file_api_bank_account_requests_proto_rawDescGZIP() []byte {
	file_api_bank_account_requests_proto_rawDescOnce.Do(func() {
		file_api_bank_account_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bank_account_requests_proto_rawDesc), len(file_api_bank_account_requests_proto_rawDesc)))
	})
	return file_api_bank_account_requests_proto_rawDescData
}

var file_api_bank_account_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_bank_account_requests_proto_goTypes = []any{
	(*CreateBankAccountRequest)(nil),   // 0: api.CreateBankAccountRequest
	(*UpdateBankAccountRequest)(nil),   // 1: api.UpdateBankAccountRequest
	(*dictionaries.ReferenceItem)(nil), // 2: dictionaries.ReferenceItem
	(*dictionaries.Bank)(nil),          // 3: dictionaries.Bank
}
var file_api_bank_account_requests_proto_depIdxs = []int32{
	2, // 0: api.CreateBankAccountRequest.currency:type_name -> dictionaries.ReferenceItem
	3, // 1: api.CreateBankAccountRequest.bank:type_name -> dictionaries.Bank
	2, // 2: api.UpdateBankAccountRequest.currency:type_name -> dictionaries.ReferenceItem
	3, // 3: api.UpdateBankAccountRequest.bank:type_name -> dictionaries.Bank
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_bank_account_requests_proto_init() }
func file_api_bank_account_requests_proto_init() {
	if File_api_bank_account_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bank_account_requests_proto_rawDesc), len(file_api_bank_account_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_bank_account_requests_proto_goTypes,
		DependencyIndexes: file_api_bank_account_requests_proto_depIdxs,
		MessageInfos:      file_api_bank_account_requests_proto_msgTypes,
	}.Build()
	File_api_bank_account_requests_proto = out.File
	file_api_bank_account_requests_proto_goTypes = nil
	file_api_bank_account_requests_proto_depIdxs = nil
}
