// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/catalog_requests.proto

package api

import (
	dictionaries "github.com/rusgainew/tunduck-app-mk/proto-lib/dictionaries"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateCatalogRequest представляет запрос на создание элемента справочника.
// Используется для POST запроса /api/command/legal-person/catalog/create
type CreateCatalogRequest struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Name               string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number             string                      `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	TnvedCode          string                      `protobuf:"bytes,3,opt,name=tnved_code,json=tnvedCode,proto3" json:"tnved_code,omitempty"`
	GkedCode           string                      `protobuf:"bytes,4,opt,name=gked_code,json=gkedCode,proto3" json:"gked_code,omitempty"`
	UnitClassification *dictionaries.ReferenceItem `protobuf:"bytes,5,opt,name=unit_classification,json=unitClassification,proto3" json:"unit_classification,omitempty"`
	CatalogType        *dictionaries.ReferenceItem `protobuf:"bytes,6,opt,name=catalog_type,json=catalogType,proto3" json:"catalog_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCatalogRequest) Reset() {
	*x = CreateCatalogRequest{}
	mi := &file_api_catalog_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogRequest) ProtoMessage() {}

func (x *CreateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_requests_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCatalogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCatalogRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateCatalogRequest) GetTnvedCode() string {
	if x != nil {
		return x.TnvedCode
	}
	return ""
}

func (x *CreateCatalogRequest) GetGkedCode() string {
	if x != nil {
		return x.GkedCode
	}
	return ""
}

func (x *CreateCatalogRequest) GetUnitClassification() *dictionaries.ReferenceItem {
	if x != nil {
		return x.UnitClassification
	}
	return nil
}

func (x *CreateCatalogRequest) GetCatalogType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.CatalogType
	}
	return nil
}

// UpdateCatalogRequest представляет запрос на обновление элемента справочника.
// Используется для PUT запроса /api/command/legal-person/catalog/edit/{id}
type UpdateCatalogRequest struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Id                 int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Number             string                      `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	TnvedCode          string                      `protobuf:"bytes,4,opt,name=tnved_code,json=tnvedCode,proto3" json:"tnved_code,omitempty"`
	GkedCode           string                      `protobuf:"bytes,5,opt,name=gked_code,json=gkedCode,proto3" json:"gked_code,omitempty"`
	UnitClassification *dictionaries.ReferenceItem `protobuf:"bytes,6,opt,name=unit_classification,json=unitClassification,proto3" json:"unit_classification,omitempty"`
	CatalogType        *dictionaries.ReferenceItem `protobuf:"bytes,7,opt,name=catalog_type,json=catalogType,proto3" json:"catalog_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateCatalogRequest) Reset() {
	*x = UpdateCatalogRequest{}
	mi := &file_api_catalog_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogRequest) ProtoMessage() {}

func (x *UpdateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_requests_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCatalogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCatalogRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCatalogRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *UpdateCatalogRequest) GetTnvedCode() string {
	if x != nil {
		return x.TnvedCode
	}
	return ""
}

func (x *UpdateCatalogRequest) GetGkedCode() string {
	if x != nil {
		return x.GkedCode
	}
	return ""
}

func (x *UpdateCatalogRequest) GetUnitClassification() *dictionaries.ReferenceItem {
	if x != nil {
		return x.UnitClassification
	}
	return nil
}

func (x *UpdateCatalogRequest) GetCatalogType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.CatalogType
	}
	return nil
}

var File_api_catalog_requests_proto protoreflect.FileDescriptor

const file_api_catalog_requests_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/catalog_requests.proto\x12\x03api\x1a!dictionaries/reference_item.proto\"\x8c\x02\n" +
	"\x14CreateCatalogRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x1d\n" +
	"\n" +
	"tnved_code\x18\x03 \x01(\tR\ttnvedCode\x12\x1b\n" +
	"\tgked_code\x18\x04 \x01(\tR\bgkedCode\x12L\n" +
	"\x13unit_classification\x18\x05 \x01(\v2\x1b.dictionaries.ReferenceItemR\x12unitClassification\x12>\n" +
	"\fcatalog_type\x18\x06 \x01(\v2\x1b.dictionaries.ReferenceItemR\vcatalogType\"\x9c\x02\n" +
	"\x14UpdateCatalogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x1d\n" +
	"\n" +
	"tnved_code\x18\x04 \x01(\tR\ttnvedCode\x12\x1b\n" +
	"\tgked_code\x18\x05 \x01(\tR\bgkedCode\x12L\n" +
	"\x13unit_classification\x18\x06 \x01(\v2\x1b.dictionaries.ReferenceItemR\x12unitClassification\x12>\n" +
	"\fcatalog_type\x18\a \x01(\v2\x1b.dictionaries.ReferenceItemR\vcatalogTypeB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var (
	file_api_catalog_requests_proto_rawDescOnce sync.Once
	file_api_catalog_requests_proto_rawDescData []byte
)

func file_api_catalog_requests_proto_rawDescGZIP() []byte {
	file_api_catalog_requests_proto_rawDescOnce.Do(func() {
		file_api_catalog_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_catalog_requests_proto_rawDesc), len(file_api_catalog_requests_proto_rawDesc)))
	})
	return file_api_catalog_requests_proto_rawDescData
}

var file_api_catalog_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_catalog_requests_proto_goTypes = []any{
	(*CreateCatalogRequest)(nil),       // 0: api.CreateCatalogRequest
	(*UpdateCatalogRequest)(nil),       // 1: api.UpdateCatalogRequest
	(*dictionaries.ReferenceItem)(nil), // 2: dictionaries.ReferenceItem
}
var file_api_catalog_requests_proto_depIdxs = []int32{
	2, // 0: api.CreateCatalogRequest.unit_classification:type_name -> dictionaries.ReferenceItem
	2, // 1: api.CreateCatalogRequest.catalog_type:type_name -> dictionaries.ReferenceItem
	2, // 2: api.UpdateCatalogRequest.unit_classification:type_name -> dictionaries.ReferenceItem
	2, // 3: api.UpdateCatalogRequest.catalog_type:type_name -> dictionaries.ReferenceItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_catalog_requests_proto_init() }
func file_api_catalog_requests_proto_init() {
	if File_api_catalog_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_catalog_requests_proto_rawDesc), len(file_api_catalog_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_catalog_requests_proto_goTypes,
		DependencyIndexes: file_api_catalog_requests_proto_depIdxs,
		MessageInfos:      file_api_catalog_requests_proto_msgTypes,
	}.Build()
	File_api_catalog_requests_proto = out.File
	file_api_catalog_requests_proto_goTypes = nil
	file_api_catalog_requests_proto_depIdxs = nil
}
