// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/foreign_company_requests.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateForeignCompanyRequest представляет запрос на создание иностранной компании.
// Используется для POST запроса /api/command/foreign-company/create
type CreateForeignCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           string                 `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForeignCompanyRequest) Reset() {
	*x = CreateForeignCompanyRequest{}
	mi := &file_api_foreign_company_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForeignCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForeignCompanyRequest) ProtoMessage() {}

func (x *CreateForeignCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foreign_company_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForeignCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateForeignCompanyRequest) Descriptor() ([]byte, []int) {
	return file_api_foreign_company_requests_proto_rawDescGZIP(), []int{0}
}

func (x *CreateForeignCompanyRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *CreateForeignCompanyRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

// UpdateForeignCompanyRequest представляет запрос на обновление иностранной компании.
// Используется для PUT запроса /api/command/foreign-company/edit/{id}
type UpdateForeignCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateForeignCompanyRequest) Reset() {
	*x = UpdateForeignCompanyRequest{}
	mi := &file_api_foreign_company_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateForeignCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateForeignCompanyRequest) ProtoMessage() {}

func (x *UpdateForeignCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_foreign_company_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateForeignCompanyRequest.ProtoReflect.Descriptor instead.
func (*UpdateForeignCompanyRequest) Descriptor() ([]byte, []int) {
	return file_api_foreign_company_requests_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateForeignCompanyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateForeignCompanyRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *UpdateForeignCompanyRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_api_foreign_company_requests_proto protoreflect.FileDescriptor

const file_api_foreign_company_requests_proto_rawDesc = "" +
	"\n" +
	"\"api/foreign_company_requests.proto\x12\x03api\"L\n" +
	"\x1bCreateForeignCompanyRequest\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\tR\x03pin\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\"\\\n" +
	"\x1bUpdateForeignCompanyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullNameB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var (
	file_api_foreign_company_requests_proto_rawDescOnce sync.Once
	file_api_foreign_company_requests_proto_rawDescData []byte
)

func file_api_foreign_company_requests_proto_rawDescGZIP() []byte {
	file_api_foreign_company_requests_proto_rawDescOnce.Do(func() {
		file_api_foreign_company_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_foreign_company_requests_proto_rawDesc), len(file_api_foreign_company_requests_proto_rawDesc)))
	})
	return file_api_foreign_company_requests_proto_rawDescData
}

var file_api_foreign_company_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_foreign_company_requests_proto_goTypes = []any{
	(*CreateForeignCompanyRequest)(nil), // 0: api.CreateForeignCompanyRequest
	(*UpdateForeignCompanyRequest)(nil), // 1: api.UpdateForeignCompanyRequest
}
var file_api_foreign_company_requests_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_foreign_company_requests_proto_init() }
func file_api_foreign_company_requests_proto_init() {
	if File_api_foreign_company_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_foreign_company_requests_proto_rawDesc), len(file_api_foreign_company_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_foreign_company_requests_proto_goTypes,
		DependencyIndexes: file_api_foreign_company_requests_proto_depIdxs,
		MessageInfos:      file_api_foreign_company_requests_proto_msgTypes,
	}.Build()
	File_api_foreign_company_requests_proto = out.File
	file_api_foreign_company_requests_proto_goTypes = nil
	file_api_foreign_company_requests_proto_depIdxs = nil
}
