// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/invoice_requests.proto

package api

import (
	dictionaries "github.com/rusgainew/tunduck-app-mk/proto-lib/dictionaries"
	entities "github.com/rusgainew/tunduck-app-mk/proto-lib/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateInvoiceRequest представляет запрос на создание счета-фактуры.
// Используется для POST запроса /api/command/invoice/{type}/create
type CreateInvoiceRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	InvoiceNumber string                      `protobuf:"bytes,1,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	InvoiceDate   *wrapperspb.StringValue     `protobuf:"bytes,2,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	DeliveryDate  *wrapperspb.StringValue     `protobuf:"bytes,3,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"`
	TotalAmount   float64                     `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	IsResident    bool                        `protobuf:"varint,5,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	Note          string                      `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	LegalPerson   *entities.Party             `protobuf:"bytes,7,opt,name=legal_person,json=legalPerson,proto3" json:"legal_person,omitempty"`
	Contractor    *entities.Party             `protobuf:"bytes,8,opt,name=contractor,proto3" json:"contractor,omitempty"`
	Currency      *dictionaries.ReferenceItem `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentType   *dictionaries.ReferenceItem `protobuf:"bytes,10,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	DeliveryType  *dictionaries.ReferenceItem `protobuf:"bytes,11,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	VatTaxType    *dictionaries.VATTaxType    `protobuf:"bytes,12,opt,name=vat_tax_type,json=vatTaxType,proto3" json:"vat_tax_type,omitempty"`
	Details       []*entities.InvoiceDetail   `protobuf:"bytes,13,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_api_invoice_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_invoice_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_api_invoice_requests_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInvoiceRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *CreateInvoiceRequest) GetInvoiceDate() *wrapperspb.StringValue {
	if x != nil {
		return x.InvoiceDate
	}
	return nil
}

func (x *CreateInvoiceRequest) GetDeliveryDate() *wrapperspb.StringValue {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

func (x *CreateInvoiceRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateInvoiceRequest) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

func (x *CreateInvoiceRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateInvoiceRequest) GetLegalPerson() *entities.Party {
	if x != nil {
		return x.LegalPerson
	}
	return nil
}

func (x *CreateInvoiceRequest) GetContractor() *entities.Party {
	if x != nil {
		return x.Contractor
	}
	return nil
}

func (x *CreateInvoiceRequest) GetCurrency() *dictionaries.ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *CreateInvoiceRequest) GetPaymentType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.PaymentType
	}
	return nil
}

func (x *CreateInvoiceRequest) GetDeliveryType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.DeliveryType
	}
	return nil
}

func (x *CreateInvoiceRequest) GetVatTaxType() *dictionaries.VATTaxType {
	if x != nil {
		return x.VatTaxType
	}
	return nil
}

func (x *CreateInvoiceRequest) GetDetails() []*entities.InvoiceDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// UpdateInvoiceRequest представляет запрос на обновление/редактирование счета-фактуры.
// Используется для PUT запроса /api/command/invoice/{type}/edit/{id}
type UpdateInvoiceRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNumber string                      `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	InvoiceDate   *wrapperspb.StringValue     `protobuf:"bytes,3,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	DeliveryDate  *wrapperspb.StringValue     `protobuf:"bytes,4,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"`
	TotalAmount   float64                     `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	IsResident    bool                        `protobuf:"varint,6,opt,name=is_resident,json=isResident,proto3" json:"is_resident,omitempty"`
	Note          string                      `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Currency      *dictionaries.ReferenceItem `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentType   *dictionaries.ReferenceItem `protobuf:"bytes,9,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	DeliveryType  *dictionaries.ReferenceItem `protobuf:"bytes,10,opt,name=delivery_type,json=deliveryType,proto3" json:"delivery_type,omitempty"`
	VatTaxType    *dictionaries.VATTaxType    `protobuf:"bytes,11,opt,name=vat_tax_type,json=vatTaxType,proto3" json:"vat_tax_type,omitempty"`
	Details       []*entities.InvoiceDetail   `protobuf:"bytes,12,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvoiceRequest) Reset() {
	*x = UpdateInvoiceRequest{}
	mi := &file_api_invoice_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvoiceRequest) ProtoMessage() {}

func (x *UpdateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_invoice_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_api_invoice_requests_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateInvoiceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInvoiceRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *UpdateInvoiceRequest) GetInvoiceDate() *wrapperspb.StringValue {
	if x != nil {
		return x.InvoiceDate
	}
	return nil
}

func (x *UpdateInvoiceRequest) GetDeliveryDate() *wrapperspb.StringValue {
	if x != nil {
		return x.DeliveryDate
	}
	return nil
}

func (x *UpdateInvoiceRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *UpdateInvoiceRequest) GetIsResident() bool {
	if x != nil {
		return x.IsResident
	}
	return false
}

func (x *UpdateInvoiceRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateInvoiceRequest) GetCurrency() *dictionaries.ReferenceItem {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *UpdateInvoiceRequest) GetPaymentType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.PaymentType
	}
	return nil
}

func (x *UpdateInvoiceRequest) GetDeliveryType() *dictionaries.ReferenceItem {
	if x != nil {
		return x.DeliveryType
	}
	return nil
}

func (x *UpdateInvoiceRequest) GetVatTaxType() *dictionaries.VATTaxType {
	if x != nil {
		return x.VatTaxType
	}
	return nil
}

func (x *UpdateInvoiceRequest) GetDetails() []*entities.InvoiceDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// AcceptOrRejectRequest представляет запрос на принятие или отклонение счета-фактуры.
// Используется для POST запроса /api/command/invoice/{type}/accept-or-reject
type AcceptOrRejectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentUuid  string                 `protobuf:"bytes,1,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrRejectRequest) Reset() {
	*x = AcceptOrRejectRequest{}
	mi := &file_api_invoice_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrRejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrRejectRequest) ProtoMessage() {}

func (x *AcceptOrRejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_invoice_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrRejectRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrRejectRequest) Descriptor() ([]byte, []int) {
	return file_api_invoice_requests_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptOrRejectRequest) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

func (x *AcceptOrRejectRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *AcceptOrRejectRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// RevokeRequest представляет запрос на отзыв (отмену) документа.
// Используется для POST запроса /api/command/invoice/{type}/revoke
type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentUuid  string                 `protobuf:"bytes,1,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_api_invoice_requests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_invoice_requests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_api_invoice_requests_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeRequest) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

// SignRequest представляет запрос на подписание документа.
// Используется для POST запроса /api/command/invoice/{type}/sign
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentUuid  string                 `protobuf:"bytes,1,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_api_invoice_requests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_invoice_requests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_api_invoice_requests_proto_rawDescGZIP(), []int{4}
}

func (x *SignRequest) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

func (x *SignRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_api_invoice_requests_proto protoreflect.FileDescriptor

const file_api_invoice_requests_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/invoice_requests.proto\x12\x03api\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x14entities/party.proto\x1a\x1dentities/invoice_detail.proto\x1a!dictionaries/reference_item.proto\x1a\x1fdictionaries/vat_tax_type.proto\"\xa8\x05\n" +
	"\x14CreateInvoiceRequest\x12%\n" +
	"\x0einvoice_number\x18\x01 \x01(\tR\rinvoiceNumber\x12?\n" +
	"\finvoice_date\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vinvoiceDate\x12A\n" +
	"\rdelivery_date\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\fdeliveryDate\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x1f\n" +
	"\vis_resident\x18\x05 \x01(\bR\n" +
	"isResident\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x122\n" +
	"\flegal_person\x18\a \x01(\v2\x0f.entities.PartyR\vlegalPerson\x12/\n" +
	"\n" +
	"contractor\x18\b \x01(\v2\x0f.entities.PartyR\n" +
	"contractor\x127\n" +
	"\bcurrency\x18\t \x01(\v2\x1b.dictionaries.ReferenceItemR\bcurrency\x12>\n" +
	"\fpayment_type\x18\n" +
	" \x01(\v2\x1b.dictionaries.ReferenceItemR\vpaymentType\x12@\n" +
	"\rdelivery_type\x18\v \x01(\v2\x1b.dictionaries.ReferenceItemR\fdeliveryType\x12:\n" +
	"\fvat_tax_type\x18\f \x01(\v2\x18.dictionaries.VATTaxTypeR\n" +
	"vatTaxType\x121\n" +
	"\adetails\x18\r \x03(\v2\x17.entities.InvoiceDetailR\adetails\"\xd3\x04\n" +
	"\x14UpdateInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12?\n" +
	"\finvoice_date\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vinvoiceDate\x12A\n" +
	"\rdelivery_date\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\fdeliveryDate\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x1f\n" +
	"\vis_resident\x18\x06 \x01(\bR\n" +
	"isResident\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x127\n" +
	"\bcurrency\x18\b \x01(\v2\x1b.dictionaries.ReferenceItemR\bcurrency\x12>\n" +
	"\fpayment_type\x18\t \x01(\v2\x1b.dictionaries.ReferenceItemR\vpaymentType\x12@\n" +
	"\rdelivery_type\x18\n" +
	" \x01(\v2\x1b.dictionaries.ReferenceItemR\fdeliveryType\x12:\n" +
	"\fvat_tax_type\x18\v \x01(\v2\x18.dictionaries.VATTaxTypeR\n" +
	"vatTaxType\x121\n" +
	"\adetails\x18\f \x03(\v2\x17.entities.InvoiceDetailR\adetails\"y\n" +
	"\x15AcceptOrRejectRequest\x12#\n" +
	"\rdocument_uuid\x18\x01 \x01(\tR\fdocumentUuid\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"4\n" +
	"\rRevokeRequest\x12#\n" +
	"\rdocument_uuid\x18\x01 \x01(\tR\fdocumentUuid\"P\n" +
	"\vSignRequest\x12#\n" +
	"\rdocument_uuid\x18\x01 \x01(\tR\fdocumentUuid\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignatureB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var (
	file_api_invoice_requests_proto_rawDescOnce sync.Once
	file_api_invoice_requests_proto_rawDescData []byte
)

func file_api_invoice_requests_proto_rawDescGZIP() []byte {
	file_api_invoice_requests_proto_rawDescOnce.Do(func() {
		file_api_invoice_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_invoice_requests_proto_rawDesc), len(file_api_invoice_requests_proto_rawDesc)))
	})
	return file_api_invoice_requests_proto_rawDescData
}

var file_api_invoice_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_invoice_requests_proto_goTypes = []any{
	(*CreateInvoiceRequest)(nil),       // 0: api.CreateInvoiceRequest
	(*UpdateInvoiceRequest)(nil),       // 1: api.UpdateInvoiceRequest
	(*AcceptOrRejectRequest)(nil),      // 2: api.AcceptOrRejectRequest
	(*RevokeRequest)(nil),              // 3: api.RevokeRequest
	(*SignRequest)(nil),                // 4: api.SignRequest
	(*wrapperspb.StringValue)(nil),     // 5: google.protobuf.StringValue
	(*entities.Party)(nil),             // 6: entities.Party
	(*dictionaries.ReferenceItem)(nil), // 7: dictionaries.ReferenceItem
	(*dictionaries.VATTaxType)(nil),    // 8: dictionaries.VATTaxType
	(*entities.InvoiceDetail)(nil),     // 9: entities.InvoiceDetail
}
var file_api_invoice_requests_proto_depIdxs = []int32{
	5,  // 0: api.CreateInvoiceRequest.invoice_date:type_name -> google.protobuf.StringValue
	5,  // 1: api.CreateInvoiceRequest.delivery_date:type_name -> google.protobuf.StringValue
	6,  // 2: api.CreateInvoiceRequest.legal_person:type_name -> entities.Party
	6,  // 3: api.CreateInvoiceRequest.contractor:type_name -> entities.Party
	7,  // 4: api.CreateInvoiceRequest.currency:type_name -> dictionaries.ReferenceItem
	7,  // 5: api.CreateInvoiceRequest.payment_type:type_name -> dictionaries.ReferenceItem
	7,  // 6: api.CreateInvoiceRequest.delivery_type:type_name -> dictionaries.ReferenceItem
	8,  // 7: api.CreateInvoiceRequest.vat_tax_type:type_name -> dictionaries.VATTaxType
	9,  // 8: api.CreateInvoiceRequest.details:type_name -> entities.InvoiceDetail
	5,  // 9: api.UpdateInvoiceRequest.invoice_date:type_name -> google.protobuf.StringValue
	5,  // 10: api.UpdateInvoiceRequest.delivery_date:type_name -> google.protobuf.StringValue
	7,  // 11: api.UpdateInvoiceRequest.currency:type_name -> dictionaries.ReferenceItem
	7,  // 12: api.UpdateInvoiceRequest.payment_type:type_name -> dictionaries.ReferenceItem
	7,  // 13: api.UpdateInvoiceRequest.delivery_type:type_name -> dictionaries.ReferenceItem
	8,  // 14: api.UpdateInvoiceRequest.vat_tax_type:type_name -> dictionaries.VATTaxType
	9,  // 15: api.UpdateInvoiceRequest.details:type_name -> entities.InvoiceDetail
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_invoice_requests_proto_init() }
func file_api_invoice_requests_proto_init() {
	if File_api_invoice_requests_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_invoice_requests_proto_rawDesc), len(file_api_invoice_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_invoice_requests_proto_goTypes,
		DependencyIndexes: file_api_invoice_requests_proto_depIdxs,
		MessageInfos:      file_api_invoice_requests_proto_msgTypes,
	}.Build()
	File_api_invoice_requests_proto = out.File
	file_api_invoice_requests_proto_goTypes = nil
	file_api_invoice_requests_proto_depIdxs = nil
}
