// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/page_info.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageInfo представляет информацию о пагинации (разбиение на страницы).
// Используется в API для работы с большими списками данных,
// позволяя получать информацию порциями вместо полного списка.
//
// Пагинация необходима для:
//   - Оптимизации производительности сети и сервера
//   - Улучшения времени отклика API
//   - Управления использованием памяти при больших объемах данных
//   - Удобного отображения данных в пользовательском интерфейсе
//
// Пример использования:
//   - Запрос: GET /api/query/invoice/realization/all-documents?page=0&size=20
//   - Ответ содержит первые 20 счетов и информацию о пагинации
//
// Клиент может использовать TotalPage для подсчета, сколько страниц
// нужно загрузить для получения всех данных, и Page для навигации.
type PageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page - Номер текущей страницы (отсчет с нуля).
	// Определяет, какой набор результатов был получен.
	// Значение от 0 до (TotalPage - 1).
	// Пример: page=0 означает первую страницу, page=1 означает вторую страницу
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Size - Количество элементов на одной странице.
	// Определяет, сколько записей вернется в этом ответе.
	// Обычно устанавливается клиентом при запросе API.
	// Пример: size=20 означает, что в ответе максимум 20 элементов
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// TotalElements - Общее количество элементов во всех страницах.
	// Полное количество записей, доступных в системе.
	// Используется для расчета общего числа страниц.
	// Пример: если TotalElements=100 и Size=20, то всего 5 страниц
	TotalElements int32 `protobuf:"varint,3,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	// TotalPage - Общее количество страниц.
	// Рассчитывается как: ceil(TotalElements / Size)
	// Позволяет клиенту знать, сколько всего страниц доступно.
	// Пример: если TotalElements=100 и Size=20, то TotalPage=5
	// Клиент может загружать страницы от 0 до (TotalPage-1)
	TotalPage     int32 `protobuf:"varint,4,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_api_page_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_page_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_page_info_proto_rawDescGZIP(), []int{0}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageInfo) GetTotalElements() int32 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

func (x *PageInfo) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

var File_api_page_info_proto protoreflect.FileDescriptor

const file_api_page_info_proto_rawDesc = "" +
	"\n" +
	"\x13api/page_info.proto\x12\x03api\"x\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12%\n" +
	"\x0etotal_elements\x18\x03 \x01(\x05R\rtotalElements\x12\x1d\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x05R\ttotalPageB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var (
	file_api_page_info_proto_rawDescOnce sync.Once
	file_api_page_info_proto_rawDescData []byte
)

func file_api_page_info_proto_rawDescGZIP() []byte {
	file_api_page_info_proto_rawDescOnce.Do(func() {
		file_api_page_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_page_info_proto_rawDesc), len(file_api_page_info_proto_rawDesc)))
	})
	return file_api_page_info_proto_rawDescData
}

var file_api_page_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_page_info_proto_goTypes = []any{
	(*PageInfo)(nil), // 0: api.PageInfo
}
var file_api_page_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_page_info_proto_init() }
func file_api_page_info_proto_init() {
	if File_api_page_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_page_info_proto_rawDesc), len(file_api_page_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_page_info_proto_goTypes,
		DependencyIndexes: file_api_page_info_proto_depIdxs,
		MessageInfos:      file_api_page_info_proto_msgTypes,
	}.Build()
	File_api_page_info_proto = out.File
	file_api_page_info_proto_goTypes = nil
	file_api_page_info_proto_depIdxs = nil
}
