// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/requests.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_requests_proto protoreflect.FileDescriptor

const file_api_requests_proto_rawDesc = "" +
	"\n" +
	"\x12api/requests.proto\x12\x03api\x1a\x1aapi/invoice_requests.proto\x1a\x1fapi/bank_account_requests.proto\x1a\x1aapi/catalog_requests.proto\x1a\"api/foreign_company_requests.protoB3Z1github.com/rusgainew/tunduck-app-mk/proto-lib/apib\x06proto3"

var file_api_requests_proto_goTypes = []any{}
var file_api_requests_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_requests_proto_init() }
func file_api_requests_proto_init() {
	if File_api_requests_proto != nil {
		return
	}
	file_api_invoice_requests_proto_init()
	file_api_bank_account_requests_proto_init()
	file_api_catalog_requests_proto_init()
	file_api_foreign_company_requests_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_requests_proto_rawDesc), len(file_api_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_requests_proto_goTypes,
		DependencyIndexes: file_api_requests_proto_depIdxs,
	}.Build()
	File_api_requests_proto = out.File
	file_api_requests_proto_goTypes = nil
	file_api_requests_proto_depIdxs = nil
}
